import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.aboutUs': 'About Us',
    'nav.networkLeadership': 'Network Leadership',
    'nav.onaPlatform': 'Network Development',
    'nav.talentAssessment': 'Talent Assessment',
    'nav.platform': 'Network Development',
    'nav.solutions': 'Solutions',
    'nav.solutionsDropdown': 'Solutions',
    'nav.talentAcquisition': 'Talent Acquisition',
    'nav.leadershipInnovation': 'Leadership & Innovation',
    'nav.organizationalDynamics': 'Organizational Dynamics',
    'nav.networkSkillsLeadership': 'Network Leadership Programs',
    'nav.collaborationAnalytics': 'Network Development',
    'nav.talentSelection': 'Talent Selection & Assessment',
    'nav.methodology': 'Methodology',
    'nav.aiLabs': 'Collab Agent',
    'nav.academy': 'Network Leadership',
    'nav.process': 'Our Process',
    'nav.skills': 'Network Skills',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.cta': "Let's Talk",

    // Hero (new value proposition)
    'hero.title': 'Network Leadership',
    'hero.subtitle': 'Unlocking the full potential of the Skills-Based Organization',
    'hero.mainTitle': 'Build a Connected, Future-Ready Organization',
    'hero.mainTitleLine1': 'Build a Connected,',
    'hero.mainTitleLine2': 'Future-Ready Organization',
    'hero.mainSubtitle': 'A winning organization is built on its people and how they connect. Use our data-driven tools to empower effective leaders, break down silos, and accelerate organizational innovation.',
    'hero.exploreSolutions': 'Explore Our Solutions',
    'hero.cta': 'Book a Consultation',
    'hero.cta2': 'Our Process',
    'hero.activateNetwork': 'Activate Your Network',
    'hero.meetAgent': 'Meet the Collab Agent',
    'hero.trustedBy': 'Trusted by',
    'hero.trustedBySubtitle': 'Trusted by Forward-Thinking Organizations',

    // Homepage - The 3 Solutions
    'index.pillar1.title': 'Network Leadership Programs',
    'index.pillar1.text': 'Cultivate a \'Network Mindset\' in your leadership team. We combine deep strategic frameworks with advanced simulations acting as a \'flight simulator\' for managers. Equip your leaders to lead through influence, break down silos, and navigate complex organizational dynamics.',
    'index.pillar1.benefit1': 'Master informal influence and leadership',
    'index.pillar1.benefit2': 'Practice in a data-driven, risk-free simulation',
    'index.pillar1.benefit3': 'Accelerate cross-functional collaboration',
    'index.pillar1.button': 'Explore Our Programs',
    'index.pillar2.title': 'Network Development',
    'index.pillar2.text': 'Advanced network mapping tools that show you exactly how your teams actually work together to identify bottlenecks and reveal hidden talent.',
    'index.pillar2.button': 'Discover Network Development',
    'index.pillar3.title': 'Talent Selection & Assessment',
    'index.pillar3.text': 'Data-driven, game-based cognitive assessments to evaluate and hire candidates who have the right skills to integrate into your network.',
    'index.pillar3.button': 'Discover Talent Tools',

    // Homepage - Our Methodology
    'index.philosophy.title': 'The Org Chart is a Myth. The Network is Reality.',
    'index.philosophy.text': 'Value is no longer created in silos—it flows through invisible networks. We provide the methodology and tools to transition your company from a rigid hierarchy into an adaptable, connected ecosystem.',

    // Homepage - The Future (AI Collab Agent)
    'index.future.title': 'Meet Your Collab Agent — Design Partner Program',
    'index.future.text': 'We are currently inviting select organizations to join our early-adopter Design Partner program. The right person is already in your contacts — tell us what you\'re working on, and we\'ll help you connect with the people who can help. Our AI agent sits directly in your workflow to leverage your network effectively.',
    'index.future.badge': 'AI Labs',
    'index.future.cta': 'Become a Design Partner',
    'index.future.ctaAlt': 'Become a Design Partner',

    // Myth Section
    'myth.title': 'The Org Chart is a Myth',
    'myth.subtitle': 'The Network is Reality',
    'myth.description': 'Value is no longer created in silos — it flows through invisible networks. We help you see, understand, and optimize these hidden connections.',

    // Process
    'process.title': 'From Hidden Data to Organizational Impact',
    'process.subtitle': 'The 4-Step Process',
    'process.step1.title': 'Identify',
    'process.step1.subtitle': 'Mapping',
    'process.step1.desc': 'Find your "Invisible Heroes" — the most connected and influential people based on actual collaboration data.',
    'process.step2.title': 'Diagnose',
    'process.step2.subtitle': 'Profiling',
    'process.step2.desc': 'Assess specific relational skills: ability to build trust, exert influence, and bridge disparate groups.',
    'process.step3.title': 'Developing',
    'process.step3.subtitle': 'Skills',
    'process.step3.desc': 'Targeted development programs to strengthen network leadership capabilities.',
    'process.step4.title': 'Implementing',
    'process.step4.subtitle': 'AI Agent',
    'process.step4.desc': 'AI-powered coaching and real-time connectivity insights for continuous improvement.',

    // Skills
    'skills.title': 'The Network Mindset',
    'skills.subtitle': 'Essential Skills for Modern Leadership',
    'skills.hub.title': 'Network Hub',
    'skills.hub.desc': 'A person at the center of conversations, sought for advice and guidance. Builds high-trust relationships.',
    'skills.bridge.title': 'Strategic Bridge',
    'skills.bridge.desc': 'Connects between units, ranks, and different fields of expertise. Facilitates alignment and balance.',
    'skills.gardener.title': 'Network Gardener',
    'skills.gardener.desc': 'Maintains deep, local, continuous relationships. Strengthens high-quality relationships.',
    'skills.pioneer.title': 'Network Pioneer',
    'skills.pioneer.desc': 'Constantly searches for new connections and domains. Builds high-diversity relationships.',

    // Index
    'index.turnOrgChart': 'Turn Your Org Chart Into a Living Network',
    'index.orgChartDesc': 'Move beyond traditional org charts. We use Organizational Network Analysis (ONA) to reveal how work really gets done.',
    'index.innovation': 'Innovation & Silo Busting',
    'index.innovationDesc': 'Innovation happens at the intersection. We visualize structural holes and bridge disconnected silos to speed up ideation.',
    'index.retention': 'Retention & Burnout',
    'index.retentionDesc': 'Spot flight risks before they resign. Visualize isolated nodes (purple) vs. embedded employees to predict attrition.',
    'index.leadership': 'Network Leadership',
    'index.leadershipDesc': 'Shift from hierarchy to hub. Identify and train your central connectors to influence change and drive strategy.',
    'index.howWeDoIt': 'How We Do It',
    'index.explorePlatform': 'Explore Network Development',
    'index.risk': 'Risk',

    // Platform
    'platform.os': 'Network Development',
    'platform.title': 'Visualize the Network. Unlock True Collaboration.',
    'platform.subtitle': "We use advanced Organizational Network Analysis (ONA) to reveal your company's hidden connections, combined with an AI assistant that empowers every employee to leverage them.",
    'platform.onaEngine': 'Organizational Network Analysis (ONA)',
    'platform.visualizeInvisible': 'Map the Reality',
    'platform.onaDesc': 'We map the actual structure and flow of your organization. Our engine identifies systemic bottlenecks, isolated talent, and hidden influencers, giving leadership a clear picture of how work actually gets done.',
    'platform.onaFeature1': 'Visualize cross-functional communication flows',
    'platform.onaFeature2': 'Identify organizational bottlenecks and silos',
    'platform.onaFeature3': 'Track overall network health and integration',
    'platform.collabAgent': 'Smart Connections',
    'platform.actionableNudges': 'On-Demand Collaboration',
    'platform.agentDesc': "We shift the power directly to your employees and managers. The Collab Agent lives in their daily workflow (Teams/Slack), analyzing their immediate challenges and suggesting the exact right people to connect with to solve them.",
    'platform.agentFeature1': 'Real-time connection recommendations',
    'platform.agentFeature2': 'Based on actual organizational needs and ONA data',
    'platform.agentFeature3': 'Seamless integration into daily workflows',
    'platform.networkProfiling': 'Network Skill Development',
    'platform.deepInsight': 'Cultivate the Mindset',
    'platform.profilingDesc': 'Beyond just introductions, StepAhead helps employees understand and develop their unique "Network Persona." It provides continuous profiling and coaching to build stronger, more effective collaborative skills.',
    'platform.profilingFeature1': 'Discover personal network strengths and blind spots',
    'platform.profilingFeature2': 'Targeted coaching for network skill development',
    'platform.profilingFeature3': 'Empower managers to build high-trust teams',
    'platform.seeHowItWorks': 'See How It Works',
    'platform.readyTransform': 'Ready to Transform Your Organization?',
    'platform.joinCompanies': 'Join the forward-thinking companies already using StepAhead.',
    'platform.bookDemo': 'Book a Demo',
    'platform.contactSales': 'Contact Sales',

    // Solutions
    'solutions.badge': 'SOLUTIONS FOR EVERY CHALLENGE',
    'solutions.title': 'Solving the Complexity of Modern Work',
    'solutions.subtitle': 'From breaking down silos to navigating complex organizational changes—we turn your biggest human challenges into manageable data insights.',
    'solutions.siloBusting': 'Silo Busting & Collaboration',
    'solutions.siloDesc': 'Organizations lose millions on disconnected departments. We identify communication breaks in real-time and nudge leaders to bridge the gaps instantly.',
    'solutions.siloBenefit1': 'Increase cross-functional innovation',
    'solutions.siloBenefit2': 'Reduce duplication of work',
    'solutions.siloBenefit3': 'Speed up decision making',
    'solutions.changeManagement': 'Change Management',
    'solutions.changeDesc': "Whether it's M&A, hyper-growth, or restructuring—change fails due to people dynamics. We map the network to identify key 'Change Agents' who can accelerate adoption and integration.",
    'solutions.changeBenefit1': 'Accelerate M&A integration',
    'solutions.changeBenefit2': 'Manage rapid growth pains',
    'solutions.changeBenefit3': 'Identify cultural blockers',
    'solutions.talentRetention': 'Talent Retention & Burnout',
    'solutions.retentionDesc': 'Spot flight risks before they resign. Our AI analyzes communication patterns to detect burnout (over-collaboration) and isolation (disengagement) early.',
    'solutions.retentionBenefit1': 'Predict burnout risk',
    'solutions.retentionBenefit2': 'Identify isolated high-performers',
    'solutions.retentionBenefit3': 'Improve manager-employee connection',
    'solutions.leadershipDev': 'Network Leadership Development',
    'solutions.leadershipDesc': "Hierarchy is dead. We measure and train managers on how to become 'Hubs' of trust and influence, using data-driven insights and gamified simulations.",
    'solutions.leadershipBenefit1': 'Move from command to connect',
    'solutions.leadershipBenefit2': 'Visualize leadership impact',
    'solutions.leadershipBenefit3': 'Data-driven coaching plans',
    'solutions.seeHowItWorks': 'See How It Works',
    'solutions.dontSlowDown': "Don't let invisible problems slow you down",
    'solutions.getStrategy': 'Get a Strategy Session',

    // Assessment
    'assessment.badge': 'AI-SUPPORTED TALENT ASSESSMENT',
    'assessment.title': 'Game-Based Assessments for Recruitment & Evaluation',
    'assessment.subtitle': "Accelium's assessment tests are based on smart thinking games that require candidates to analyze data, plan, solve problems, and make diverse decisions. The system analyzes the problem-solving methods and decisions made by the candidate during the game, characterizing their thinking patterns and operational style. The assessment report presents a multidimensional skill profile that allows for accurate identification of each candidate's strengths and weaknesses.",
    'assessment.skillsTitle': 'Measuring 23 Core Cognitive & Behavioral Skills',
    'assessment.skillsDesc': 'Our dynamic game environments assess a broad spectrum of complex skills in real-time.',
    'assessment.experienceTitle': 'The Candidate Experience',
    'assessment.experienceSubtitle': 'Authentic Behavior, Not Rehearsed Answers',
    'assessment.experienceDesc': 'Provide a positive, innovative testing experience. No prior knowledge or instruction is required—game rules are learned dynamically, mirroring how candidates adapt to new challenges in the workplace.',
    'assessment.reportsTitle': 'Deep-Dive Analytics & Reports',
    'assessment.reportsSubtitle': 'Data You Won\'t Find Anywhere Else',
    'assessment.reportsDesc': 'Generate multidimensional skill profiles, group performance analytics, and actionable AI insights. Instantly identify strengths, blind spots, and cultural fit.',
    'assessment.ctaTitle': 'Ready to transform your hiring & evaluation?',
    'assessment.ctaDesc': 'Get a comprehensive skill profile compared to global benchmarks for every candidate.',
    'assessment.ctaButton': 'Book a Demo',
    'assessment.skill1': 'Pattern Recognition',
    'assessment.skill2': 'Taking Initiative',
    'assessment.skill3': 'Solving Complex Problems',
    'assessment.skill4': 'Resourcefulness',
    'assessment.skill5': 'Identifying Opportunities',
    'assessment.skill6': 'Systemic Vision',
    'assessment.skill7': 'Planning',
    'assessment.skill8': 'Learning Aptitude',
    'assessment.skill9': 'Mindfulness',
    'assessment.skill10': 'Data Analysis',
    'assessment.skill11': 'Flexible Thinking',
    'assessment.skill12': 'Coping with Changes',
    'assessment.skill13': 'Dealing with Time Pressure',
    'assessment.skill14': 'Developing a Plan',
    'assessment.skill15': 'Risk Management',
    'assessment.skill16': 'Strategic Execution',
    'assessment.skill17': 'Adaptability',
    'assessment.skill18': 'Decision Making',
    'assessment.skill19': 'Cognitive Flexibility',
    'assessment.skill20': 'Execution Focus',
    'assessment.skill21': 'Resilience',
    'assessment.skill22': 'Creative Problem Solving',
    'assessment.skill23': 'Information Filtering',
    'assessment.poweredBy': 'Powered by Accelium',
    'assessment.downloadResearch': 'Download Validation Research',
    'assessment.downloadReport': 'Download Sample Report',

    // Academy
    'academy.badge': 'PRACTICAL LEADERSHIP WORKSHOPS',
    'academy.title': 'Network Leadership Programs',
    'academy.subtitle': 'Practical workshops for the new era of management. We help leaders shift from a hierarchical mindset to a networked one, using advanced simulations and practical tools.',
    'academy.downloadSyllabus': 'Download Syllabus',
    'academy.methodology.tag': 'The Network Mindset',
    'academy.methodology.title': 'Cultivating the Networked Leader',
    'academy.methodology.desc1': 'The modern organization is no longer a rigid hierarchy; it is a complex, living human network. Our methodology is rooted in developing a "Network Mindset"—equipping leaders with the perspective to see beyond the traditional org chart and understand the actual flow of trust, information, and influence.',
    'academy.methodology.desc2': 'To turn these deep strategic concepts into actionable skills, we leverage high-end technology. Through advanced network mapping simulations and cognitive thinking games, we create a highly engaging "flight simulator" for management. These immersive tools allow leaders to practice complex organizational dynamics in a safe, data-driven environment.',
    'academy.methodology.bullet1': 'Network Awareness & Strategic Perspective',
    'academy.methodology.bullet2': 'Real-Time Data-Driven Reflection',
    'academy.methodology.bullet3': 'Immediate Real-World Application',
    'academy.strategicSimulations': 'Strategic Simulations',
    'academy.interactiveTraining': 'Interactive Training Aid',
    'academy.coreModules': 'Our Core Workshops',
    'academy.developingPillars': 'A structured, sequential process to develop your management DNA.',
    'academy.w1.title': '01. Intro to Network Leadership',
    'academy.w1.desc': 'Powered by Network Mapping Simulations. We uncover the hidden informal structure of your organization. Leaders learn to identify knowledge hubs, hidden talent, and bottlenecks that hinder growth.',
    'academy.w2.title': '02. Influence & Courage',
    'academy.w2.desc': 'Powered by Network Mapping Simulations. Master the art of leading without formal authority. Participants learn to leverage their network position to drive change and promote cross-organizational initiatives.',
    'academy.w3.title': '03. Trust & Psychological Safety',
    'academy.w3.desc': 'Powered by Network Mapping Simulations. Shift from a departmental mindset to a systemic view. We use real data to bridge structural holes and generate true synergy between isolated teams.',
    'academy.w4.title': '04. Adaptability to Change',
    'academy.w4.desc': 'Powered by Thinking Game Simulations. Adapt to rapidly changing business environments and practice decision-making under uncertainty. Experience complex dilemmas that require rapid opportunity identification.',
    'academy.w5.title': '05. Creative Thinking',
    'academy.w5.desc': 'Powered by Thinking Game Simulations. Maximize outcomes in an environment of limited resources. Practice consensus-building, conflict resolution, and crafting complex win-win solutions.',
    'academy.w6.title': '06. Decision Making',
    'academy.w6.desc': 'Powered by Thinking Game Simulations. Build deep psychological safety within teams. Experientially demonstrate how individual actions impact collective outcomes and group cohesion.',
    'academy.upgradeDNA': 'Upgrade Your Management DNA',
    'academy.upgradeDesc': 'Equip your leaders with the skills they need to navigate a networked world.',
    'academy.bookWorkshop': 'Book a Workshop',

    // Leadership (Network Leadership / workshops catalog page)
    'leadership.hero.title': 'Skills Development & Network Leadership',
    'leadership.hero.subtitle':
      "Developing managers and key teams through experiential learning, game simulations, and building a cross-organizational 'network mindset'. We prepare today's talent for tomorrow's management challenges, providing practical tools to lead in a changing reality.",
    'leadership.hero.cta': 'View the workshop catalog',
    'leadership.hero.imageAlt': 'Leadership development workshop',
    'leadership.logosTitle': 'Our workshops drive leading organizations forward',
    'leadership.catalog.title': 'Power Skills: Workshops Catalog',
    'leadership.catalog.subtitle':
      'Network leadership and Power Skills—tailored for executive and core talent teams.',
    'leadership.cardFormat': '📍 פרונטלי | 💻 Online',
    'leadership.readMore': 'Read more',
    'leadership.badge.networkMindset': 'Network Mindset',
    'leadership.badge.powerSkills': 'Power Skills',
    'leadership.workshop.1.title': 'Network Leadership',
    'leadership.workshop.1.shortDesc':
      'Moving from hierarchical to network leadership; building organizational resilience and cognitive agility. (Includes a personal profile assessment.)',
    'leadership.workshop.1.syllabus':
      'In a world where the organizational chart no longer tells the whole story, managers must lead through networks. This workshop provides practical tools to transition from rigid hierarchical management to flexible network leadership. We will learn how to map the informal network, break down silos, identify hidden talents, and build organizational resilience.',
    'leadership.workshop.2.title': 'Influence & Managerial Courage',
    'leadership.workshop.2.shortDesc':
      'How do you influence inside and outside the organization? Practical tools for building influence and using networks as a managerial lever.',
    'leadership.workshop.2.syllabus':
      'The greatest challenge for matrix managers is driving processes without direct authority. This workshop explores the intersection of influence and managerial courage. Participants will acquire 360-degree management tools, learn to leverage the organizational network to expand their circle of influence, and develop the courage to lead complex initiatives.',
    'leadership.workshop.3.title': 'Psychological Safety & Trust',
    'leadership.workshop.3.shortDesc':
      'Creating a supportive, productive environment that enables positive relationships and effective team leadership.',
    'leadership.workshop.3.syllabus':
      'High-performing teams rely on a foundation of trust, but during times of stress, psychological safety quickly erodes. This workshop gives managers daily practices to create a safe work environment that encourages calculated risk-taking and innovation, demonstrating how authentic connection directly drives productivity.',
    'leadership.workshop.4.title': 'Adaptability & Cognitive Flexibility',
    'leadership.workshop.4.shortDesc':
      'Developing cognitive flexibility to respond and adapt quickly in a world of uncertainty.',
    'leadership.workshop.4.syllabus':
      "In a volatile business reality, the ability to adapt quickly is a critical competitive advantage. This workshop goes beyond behavioral change, focusing on developing cognitive flexibility. Managers will learn to identify and remove cognitive barriers to change, make decisions under uncertainty, and manage their team's adaptability.",
    'leadership.workshop.5.title': 'Creative Thinking',
    'leadership.workshop.5.shortDesc':
      'Challenging assumptions, expanding the solution space, and shifting routine thinking patterns.',
    'leadership.workshop.5.syllabus':
      'When standard procedures stop working, managers must know how to innovate. Using game-based learning, this workshop challenges our basic assumptions and automatic thinking patterns. Participants will practice techniques to break mental locks, expand the solution space for complex challenges, and adopt creative thinking habits.',
    'leadership.workshop.6.title': 'Decision Making',
    'leadership.workshop.6.shortDesc':
      'Navigating complex decision processes and understanding common cognitive biases.',
    'leadership.workshop.6.syllabus':
      'Managers face a constant stream of decisions, often amidst noise or lacking critical information. This workshop breaks down the psychological mechanisms of decision-making and exposes common cognitive biases. Participants will learn models for filtering noise, utilizing the "wisdom of crowds," and making fast, data-driven decisions under pressure.',
    'leadership.tech.sectionTitle': 'The Technology Behind Our Workshops',
    'leadership.tech.ona.label': 'Network Intelligence (ONA)',
    'leadership.tech.game.label': 'Game-Based Learning',
    'leadership.flexible.title': "When face-to-face isn't an option: Interactive Online Workshops",
    'leadership.flexible.body':
      'All our development programs are fully adapted for online delivery. Using our unique game platforms and simulations, we guarantee an immersive learning experience that keeps participants engaged and active, even when working from home.',
    'leadership.flexible.imageCaption': 'Zoom / online workshop (screenshot placeholder)',
    'leadership.cta.title': "Let's design the right training for your team",
    'leadership.cta.button': 'Schedule a consultation',

    // About
    'about.mission': 'OUR MISSION',
    'about.title': 'Experts in Organizational Network Analysis (ONA).',
    'about.subtitle': 'We exist to help organizations transform traditional org charts into highly collaborative, data-driven teams.',
    'about.orgChartDead': 'Connect People, Create Value.',
    'about.longLiveNetwork': '',
    'about.story1': 'StepAhead was founded with the vision of developing innovative technology based on network analysis to enable collaboration and connect people.',
    'about.story2': 'For over a century, organizations were managed like machines: top-down, siloed, and rigid. But the world has changed. Work today is complex, collaborative, and fast-paced.',
    'about.story3': 'We combined the science of Organizational Network Analysis (ONA) with practical leadership tools to give leaders a new pair of glasses—ones that see the actual flow of trust, information, and innovation.',
    'about.whatDrivesUs': 'What Drives Us',
    'about.drive1Title': 'Connecting People',
    'about.drive1Desc': 'We believe in the power of human connection. We exist to build trust, foster genuine collaboration, and bring people together across organizational boundaries.',
    'about.drive2Title': 'Innovative Technology',
    'about.drive2Desc': 'Gut feeling is important, but data is undeniable. We use advanced Network Analysis (ONA) to map the invisible and turn complex social dynamics into clear insights.',
    'about.drive3Title': 'The Network Mindset',
    'about.drive3Desc': 'We are passionate about guiding leaders away from rigid, command-and-control hierarchies and towards adaptable, influence-based network leadership.',
    'about.meetLeadership': 'Meet the Leadership',
    'about.sharonRole': 'Founder & COO',
    'about.sharonBio': "An expert in organizational dynamics and conflict resolution. As the owner of 'Gome-Gevim', Israel's leading mediation center, Sharon ensures our technology serves the people, translating network data into actionable strategies that build trust.",
    'about.yuvalRole': 'Academic Advisor',
    'about.yuvalBio': 'A world-renowned authority on Network Theory. Chair of Leadership and Networks at WHU School of Management, Germany. Yuval provides the scientific backbone to our ONA algorithms and methodology.',
    'about.nadavRole': 'CEO',
    'about.nadavBio': "A pioneer in game-based assessment and skill development. With a background as a strategic thinking lecturer and EdTech expert, Nadav leads the vision of the 'Skills-Based Organization', focusing on uncovering hidden talent through technology.",
    'about.joinRevolution': 'Ready to take the next step?',
    'about.revolutionDesc': "Whether you are an organization looking to evolve or a partner looking to collaborate, we'd love to connect.",
    'about.contactUs': 'Contact Us',

    // Team
    'team.nadav.name': 'Nadav Agozi',
    'team.nadav.title': 'CEO',
    'team.nadav.bio': 'A pioneer in game-based assessment and skill development. With a background as a strategic thinking lecturer and EdTech expert, Nadav leads the vision of the "Skills-Based Organization", focusing on uncovering hidden talent through technology.',
    'team.sharon.name': 'Sharon Rendlich',
    'team.sharon.title': 'Founder & COO',
    'team.sharon.bio': 'An expert in organizational dynamics and conflict resolution. As the owner of "Gome-Gevim", Israel\'s leading mediation center, Sharon ensures our technology serves the people, translating network data into actionable strategies that build trust.',

    // Contact Form
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Work Email',
    'contact.form.company': 'Company Name',
    'contact.form.message': 'How can we help you?',
    'contact.form.submit': 'Send Message',

    // CTA
    'cta.title': 'Ready to Unlock Your Network Potential?',
    'cta.description': 'Discover the hidden patterns of collaboration and leadership within your organization.',
    'cta.button': 'Schedule a Demo',
    'cta.badge': 'Network Development',

    // Footer
    'footer.tagline': 'Experts in Organizational Network Analysis (ONA). We help organizations transform traditional org charts into highly collaborative, data-driven teams.',
    'footer.solutionsHeading': 'Solutions',
    'footer.networkLeadership': 'Network Leadership',
    'footer.collaborationIntelligence': 'Network Development',
    'footer.talentSelection': 'Talent Selection & Assessment',
    'footer.collabAgent': 'Collab Agent (Beta)',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.contactUs': 'Contact Us',
    'footer.followLinkedIn': 'Follow us on LinkedIn',
    'footer.location': 'Tel Aviv, Israel',
    'footer.globalOps': 'Global Operations',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.legal': 'Legal',
    'footer.cookieBanner':
      'We use cookies to improve your experience and analyze website traffic. By continuing to use this site, you agree to our use of cookies and our ',
    'footer.cookieAccept': 'Accept',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.about': 'אודותינו',
    'nav.aboutUs': 'אודותינו',
    'nav.networkLeadership': 'פיתוח מנהיגות',
    'nav.onaPlatform': 'פיתוח רשתות',
    'nav.talentAssessment': 'הערכת טאלנטים',
    'nav.platform': 'פיתוח רשתות',
    'nav.solutions': 'פתרונות',
    'nav.solutionsDropdown': 'פתרונות',
    'nav.talentAcquisition': 'גיוס טאלנטים',
    'nav.leadershipInnovation': 'מנהיגות וחדשנות',
    'nav.organizationalDynamics': 'דינמיקה ארגונית',
    'nav.networkSkillsLeadership': 'תוכניות מנהיגות רשתית',
    'nav.collaborationAnalytics': 'פיתוח רשתות',
    'nav.talentSelection': 'איתור והערכת טאלנטים',
    'nav.methodology': 'מתודולוגיה',
    'nav.aiLabs': 'Collab Agent',
    'nav.academy': 'פיתוח מנהיגות',
    'nav.process': 'התהליך שלנו',
    'nav.skills': 'כישורי רשת',
    'nav.contact': 'צור קשר',
    'nav.getStarted': 'התחילו עכשיו',
    'nav.cta': 'דברו איתנו',

    // Hero
    'hero.title': 'מנהיגות רשתית',
    'hero.subtitle': 'מימוש מלוא הפוטנציאל של הארגון מבוסס-הכישורים',
    'hero.mainTitle': 'לבנות ארגון מחובר שמוכן לאתגרי המחר',
    'hero.mainTitleLine1': 'לבנות ארגון מחובר',
    'hero.mainTitleLine2': 'שמוכן לאתגרי המחר',
    'hero.mainSubtitle': 'הדרך לארגון מנצח עוברת באנשים שלו ובאופן שבו הם מחוברים. השתמשו בכלים מבוססי הנתונים שלנו כדי לחזק מנהלים אפקטיביים, לפרק סיילואים, ולהאיץ חדשנות ארגונית.',
    'hero.exploreSolutions': 'גלו את הפתרונות שלנו',
    'hero.cta': 'קבעו שיחת ייעוץ',
    'hero.cta2': 'התהליך שלנו',
    'hero.activateNetwork': 'מנפו את הרשת שלכם',
    'hero.meetAgent': 'הכירו את Collab Agent',
    'hero.trustedBy': 'סומכים עלינו',
    'hero.trustedBySubtitle': 'ארגונים מובילים שסומכים עלינו',

    // Homepage - The 3 Solutions
    'index.pillar1.title': 'תוכניות מנהיגות רשתית',
    'index.pillar1.text': 'פיתוח \'תפיסת רשת\' אצל מנהלים. אנו משלבים מודלים אסטרטגיים עם סימולציות מתקדמות המשמשות כ\'סימולטור טיסה\' ניהולי, כדי להקנות כלים להובלה מתוך השפעה, פירוק סילוסים וניווט במורכבות הארגונית.',
    'index.pillar1.benefit1': 'פיתוח מנהיגות והשפעה ללא סמכות',
    'index.pillar1.benefit2': 'תרגול בסימולציות חווייתיות מבוססות נתונים',
    'index.pillar1.benefit3': 'האצת ממשקי עבודה ושיתופי פעולה חוצי-ארגון',
    'index.pillar1.button': 'גלו תוכניות מנהיגות',
    'index.pillar2.title': 'פיתוח רשתות',
    'index.pillar2.text': 'כלי מיפוי רשת מתקדמים שמראים בדיוק איך הצוותים והמחלקות שלכם עובדים יחד בפועל – כדי לזהות צווארי בקבוק ולחשוף טאלנטים נסתרים.',
    'index.pillar2.button': 'גלו פיתוח רשתות',
    'index.pillar3.title': 'איתור והערכת טאלנטים',
    'index.pillar3.text': 'הערכות קוגניטיביות מבוססות-משחק לזיהוי מועמדים עם הכישורים והפוטנציאל להשתלב ברשת הארגונית שלכם.',
    'index.pillar3.button': 'גלו כלי הערכה',

    // Homepage - Our Methodology
    'index.philosophy.title': 'העץ הארגוני הוא מיתוס. הרשת היא המציאות.',
    'index.philosophy.text': 'ערך כבר לא נוצר בממגורות — הוא זורם דרך רשתות בלתי נראות. אנו מספקים את המתודולוגיה והכלים להעביר את החברה שלכם מהיררכיה נוקשה למערכת עבודה גמישה ומחוברת.',

    // Homepage - The Future (AI Collab Agent)
    'index.future.title': 'הכירו את Collab Agent — תוכנית שותפי פיתוח',
    'index.future.text': 'אנו מזמינים ארגונים נבחרים להצטרף לתוכנית שותפי הפיתוח המוקדמת שלנו. האדם הנכון כבר נמצא בארגון שלכם — ספרו לנו על האתגר, ונעזור לכם להתחבר לאנשים שיכולים לעזור. סוכן ה-AI שלנו משתלב ישירות בסביבת העבודה שלכם (Teams/Slack) כדי לנצל את הרשת בצורה אפקטיבית.',
    'index.future.badge': 'AI Labs',
    'index.future.cta': 'הצטרפו כשותפי פיתוח',
    'index.future.ctaAlt': 'הצטרפו כשותפי פיתוח',

    // Myth Section
    'myth.title': 'העץ הארגוני הוא מיתוס',
    'myth.subtitle': 'הרשת היא המציאות',
    'myth.description': 'ערך כבר לא נוצר בממגורות — הוא זורם דרך רשתות בלתי נראות. אנחנו עוזרים לכם לראות, להבין ולייעל את הקשרים הנסתרים האלה.',

    // Process
    'process.title': 'מנתונים נסתרים להשפעה ארגונית',
    'process.subtitle': 'תהליך 4 השלבים',
    'process.step1.title': 'זיהוי',
    'process.step1.subtitle': 'מיפוי',
    'process.step1.desc': 'מצאו את ה"גיבורים הנסתרים" — האנשים המחוברים והמשפיעים ביותר על בסיס נתוני שיתוף פעולה אמיתיים.',
    'process.step2.title': 'אבחון',
    'process.step2.subtitle': 'אפיון רשתי',
    'process.step2.desc': 'הערכת כישורים יחסיים ספציפיים: היכולת לבנות אמון, לייצר השפעה ולגשר בין קבוצות.',
    'process.step3.title': 'פיתוח',
    'process.step3.subtitle': 'כישורים',
    'process.step3.desc': 'תוכניות פיתוח ממוקדות לחיזוק יכולות מנהיגות רשתית.',
    'process.step4.title': 'יישום',
    'process.step4.subtitle': 'סוכן AI',
    'process.step4.desc': 'ליווי אישי מבוסס AI ותובנות קישוריות בזמן אמת לשיפור מתמיד.',

    // Skills
    'skills.title': 'החשיבה הרשתית',
    'skills.subtitle': 'כישורים חיוניים למנהיגות מודרנית',
    'skills.hub.title': 'צומת מרכזי (Hub)',
    'skills.hub.desc': 'אדם במרכז השיחות, אליו פונים לייעוץ והדרכה. בונה יחסי אמון גבוהים.',
    'skills.bridge.title': 'מגשר אסטרטגי',
    'skills.bridge.desc': 'מחבר בין יחידות, דרגים ותחומי מומחיות שונים. מאפשר סנכרון ואיזון.',
    'skills.gardener.title': 'מטפח רשת (Gardener)',
    'skills.gardener.desc': 'מקיים קשרים עמוקים, מקומיים ורציפים. מחזק מערכות יחסים איכותיות.',
    'skills.pioneer.title': 'חלוץ רשת (Pioneer)',
    'skills.pioneer.desc': 'מחפש כל הזמן קשרים ותחומים חדשים. בונה רשת בעלת גיוון גבוה.',

    // Index
    'index.turnOrgChart': 'הפכו את העץ הארגוני לרשת דינמית',
    'index.orgChartDesc': 'התקדמו מעבר לתרשים ארגוני מסורתי. אנו משתמשים בניתוח רשתות ארגוניות (ONA) כדי לחשוף איך העבודה באמת מתבצעת.',
    'index.innovation': 'מהירות וחדשנות',
    'index.innovationDesc': 'חדשנות קורית בנקודות החיבור. המערכת מזהה "חורים ברשת" (Structural Holes) ומגשרת בין מחלקות מבודדות כדי להאיץ תהליכי עבודה ויצירתיות.',
    'index.retention': 'שימור טאלנטים',
    'index.retentionDesc': 'זהו עובדים מבודדים לפני שהם עוזבים. ניתוח רשתי מתקדם לחיזוי סיכוני עזיבה ושחיקה.',
    'index.leadership': 'מנהיגות מודרנית',
    'index.leadershipDesc': 'מנהלים לומדים להשפיע דרך אמון וחיבורים (Hubs), ולא רק מתוקף סמכותם.',
    'index.howWeDoIt': 'איך אנחנו עושים את זה',
    'index.explorePlatform': 'גלו פיתוח רשתות',
    'index.risk': 'ניהול סיכונים',

    // Platform
    'platform.os': 'פיתוח רשתות',
    'platform.title': 'להפוך את הרשת לגלויה. לממש את פוטנציאל הארגון.',
    'platform.subtitle': 'אנו משתמשים בניתוח רשתות ארגוניות (ONA) מתקדם כדי לחשוף את הקשרים הנסתרים של החברה שלכם, יחד עם סוכן AI שמעצים כל עובד לנצל אותם.',
    'platform.onaEngine': 'ניתוח רשתות ארגוניות (ONA)',
    'platform.visualizeInvisible': 'למפות את המציאות',
    'platform.onaDesc': 'אנו ממפים את המבנה והזרימה האמיתיים של הארגון. המערכת מזהה צווארי בקבוק מערכתיים, טאלנטים מבודדים ומוקדי השפעה, ומעניקה להנהלה תמונה ברורה של איך העבודה באמת מתבצעת.',
    'platform.onaFeature1': 'ויזואליזציה של זרימת מידע חוצת-ארגון',
    'platform.onaFeature2': 'זיהוי צווארי בקבוק וסיילואים',
    'platform.onaFeature3': 'מעקב אחר בריאות ואינטגרציית הרשת',
    'platform.collabAgent': 'חיבורים חכמים',
    'platform.actionableNudges': 'שיתוף פעולה לפי דרישה',
    'platform.agentDesc': 'אנו מעבירים את הכוח ישירות לעובדים ולמנהלים. הסוכן חי בסביבת העבודה היומיומית שלהם (Teams/Slack), מנתח את האתגרים המיידיים ומציע את האנשים הנכונים לחיבור.',
    'platform.agentFeature1': 'המלצות לחיבורים בזמן אמת',
    'platform.agentFeature2': 'מבוסס על צרכים ארגוניים ונתוני ONA',
    'platform.agentFeature3': 'אינטגרציה חלקה ליום העבודה',
    'platform.networkProfiling': 'פיתוח כישורי רשת',
    'platform.deepInsight': 'טיפוח החשיבה הרשתית',
    'platform.profilingDesc': 'StepAhead עוזרת לעובדים להבין ולפתח את ה"פרסונה הרשתית" הייחודית שלהם. דרך פרופילינג וליווי מתמשך, אנו בונים כישורי עבודה משותפת חזקים ואפקטיביים יותר.',
    'platform.profilingFeature1': 'גילוי חוזקות ונקודות עיוורון ברשת האישית',
    'platform.profilingFeature2': 'אימון ממוקד לפיתוח כישורי רשת',
    'platform.profilingFeature3': 'העצמת מנהלים לבניית צוותי אמון',
    'platform.seeHowItWorks': 'ראו איך זה עובד',
    'platform.readyTransform': 'מוכנים להפוך לארגון רשתי?',
    'platform.joinCompanies': 'הצטרפו לארגונים החדשניים שכבר משתמשים ב-StepAhead.',
    'platform.bookDemo': 'קבעו הדגמה',
    'platform.contactSales': 'דברו עם צוות המכירות',

    // Solutions
    'solutions.badge': 'פתרונות לכל אתגר ארגוני',
    'solutions.title': 'פתרונות לארגונים בצמיחה ושינוי',
    'solutions.subtitle': 'אנו הופכים את האתגרים האנושיים המורכבים ביותר - מפירוק סיילואים ועד שינויים ארגוניים - לתובנות ניתנות לפעולה.',
    'solutions.siloBusting': 'פירוק סיילואים ושיתוף פעולה',
    'solutions.siloDesc': 'ארגונים מפסידים הון על מחלקות מנותקות. אנו מזהים נתקי תקשורת בזמן אמת ומכוונים מנהלים לגשר על הפערים באופן מיידי.',
    'solutions.siloBenefit1': 'הגברת חדשנות חוצת-ארגון',
    'solutions.siloBenefit2': 'צמצום כפילויות עבודה',
    'solutions.siloBenefit3': 'האצת תהליכי קבלת החלטות',
    'solutions.changeManagement': 'ניהול שינויים (Change Management)',
    'solutions.changeDesc': "בין אם מדובר במיזוגים ורכישות (M&A) או צמיחה מהירה—שינויים נכשלים בגלל דינמיקה אנושית. אנו ממפים את הרשת כדי לאתר את 'סוכני השינוי' שיאיצו את ההטמעה.",
    'solutions.changeBenefit1': 'האצת אינטגרציית M&A',
    'solutions.changeBenefit2': 'ניהול כאבי צמיחה',
    'solutions.changeBenefit3': 'זיהוי חסמים תרבותיים',
    'solutions.talentRetention': 'שימור טאלנטים ושחיקה',
    'solutions.retentionDesc': 'זיהוי סיכוני עזיבה בזמן. ה-AI שלנו מנתח דפוסי תקשורת כדי לזהות שחיקה (עומס יתר תקשורתי) ובידוד (חוסר מעורבות) בשלבים המוקדמים.',
    'solutions.retentionBenefit1': 'חיזוי וזיהוי סכנת שחיקה',
    'solutions.retentionBenefit2': 'איתור טאלנטים מבודדים',
    'solutions.retentionBenefit3': 'חיזוק הקשר בין מנהלים לעובדים',
    'solutions.leadershipDev': 'פיתוח מנהיגות רשתית',
    'solutions.leadershipDesc': "היררכיה נוקשה היא נחלת העבר. אנו מודדים ומאמנים מנהלים להפוך למוקדים (Hubs) של אמון והשפעה, תוך שימוש בדאטה וסימולציות משחקיות.",
    'solutions.leadershipBenefit1': 'מעבר משליטה (Control) לחיבור',
    'solutions.leadershipBenefit2': 'ויזואליזציה של השפעה ניהולית',
    'solutions.leadershipBenefit3': 'תוכניות אימון מבוססות-נתונים',
    'solutions.seeHowItWorks': 'ראו איך זה עובד',
    'solutions.dontSlowDown': 'אל תתנו לבעיות סמויות לעכב אתכם',
    'solutions.getStrategy': 'קבעו פגישת אסטרטגיה',

    // Assessment
    'assessment.badge': 'הערכת טאלנטים מבוססת AI',
    'assessment.title': 'הערכה מבוססת-משחק לגיוס ופיתוח עובדים',
    'assessment.subtitle': 'מבחני ההערכה של Accelium מבוססים על משחקי חשיבה חכמים הדורשים מהנבחנים לנתח נתונים, לתכנן, לפתור בעיות ולקבל מגוון החלטות. המערכת מנתחת את דרכי הפתרון ואת ההחלטות שקיבל הנבחן במהלך המשחק ומאפיינת את צורת החשיבה וסגנון הפעולה שלו. דו"ח הבחינה מציג פרופיל מיומנויות רב-ממדי המאפשר לזהות במדויק את חוזקותיו וחולשותיו של כל נבחן.',
    'assessment.skillsTitle': 'מודדים 23 כישורים קוגניטיביים והתנהגותיים',
    'assessment.skillsDesc': 'סביבת המשחקים הדינמית שלנו מעריכה קשת רחבה של כישורים מורכבים במקביל.',
    'assessment.experienceTitle': 'חווית המועמד',
    'assessment.experienceSubtitle': 'התנהגות אותנטית, לא תשובות מתורגלות',
    'assessment.experienceDesc': 'ספקו חווית מבחן חיובית וחדשנית. אין צורך בידע מוקדם או הדרכה - חוקי המשחק נלמדים תוך כדי תנועה, בדיוק כפי שהמועמדים מסתגלים לאתגרים חדשים בסביבת העבודה.',
    'assessment.reportsTitle': 'דוחות ואנליטיקה מתקדמת',
    'assessment.reportsSubtitle': 'תובנות שלא תמצאו בשום מקום אחר',
    'assessment.reportsDesc': 'הפיקו פרופילי כישורים רב-ממדיים, ניתוחי ביצועים קבוצתיים ותובנות AI ממוקדות. זהו באופן מיידי חוזקות, נקודות עיוורון והתאמה תרבותית לארגון.',
    'assessment.ctaTitle': 'מוכנים לשדרג את תהליכי הגיוס וההערכה?',
    'assessment.ctaDesc': 'קבלו פרופיל כישורים מקיף המושווה למדדי בנצ\'מרק גלובליים עבור כל מועמד.',
    'assessment.ctaButton': 'קבעו הדגמה',
    'assessment.skill1': 'זיהוי תבניות',
    'assessment.skill2': 'נטילת יוזמה',
    'assessment.skill3': 'פתרון בעיות מורכבות',
    'assessment.skill4': 'תושייה',
    'assessment.skill5': 'זיהוי הזדמנויות',
    'assessment.skill6': 'ראייה מערכתית',
    'assessment.skill7': 'תכנון',
    'assessment.skill8': 'כושר למידה',
    'assessment.skill9': 'קשיבות',
    'assessment.skill10': 'ניתוח נתונים',
    'assessment.skill11': 'חשיבה גמישה',
    'assessment.skill12': 'התמודדות עם שינויים',
    'assessment.skill13': 'עבודה תחת לחץ זמן',
    'assessment.skill14': 'פיתוח תוכנית',
    'assessment.skill15': 'ניהול סיכונים',
    'assessment.skill16': 'ביצוע אסטרטגי',
    'assessment.skill17': 'הסתגלות',
    'assessment.skill18': 'קבלת החלטות',
    'assessment.skill19': 'גמישות קוגניטיבית',
    'assessment.skill20': 'מיקוד בביצוע',
    'assessment.skill21': 'חוסן',
    'assessment.skill22': 'פתרון בעיות יצירתי',
    'assessment.skill23': 'סינון מידע',
    'assessment.poweredBy': 'מופעל בטכנולוגיית Accelium',
    'assessment.downloadResearch': 'להורדת מחקר התוקף',
    'assessment.downloadReport': 'להורדת דוח לדוגמא',

    // Academy
    'academy.badge': 'סדנאות מנהיגות פרקטיות',
    'academy.title': 'תוכניות מנהיגות רשתית',
    'academy.subtitle': 'סדנאות מעשיות לעידן הניהול החדש. אנו עוזרים למנהיגים לעבור מתפיסה היררכית לרשתית, באמצעות סימולציות מתקדמות וכלים פרקטיים.',
    'academy.downloadSyllabus': 'הורידו את הסילבוס',
    'academy.methodology.tag': 'תפיסת הרשת',
    'academy.methodology.title': 'פיתוח מנהיגות רשתית',
    'academy.methodology.desc1': 'הארגון המודרני אינו עוד היררכיה נוקשה, אלא רשת אנושית מורכבת. המתודולוגיה שלנו מושתתת על פיתוח "תפיסת רשת" (Network Mindset) – הקניית יכולת למנהלים לראות מעבר לתרשים הארגוני ולהבין את הזרימה האמיתית של אמון, מידע והשפעה.',
    'academy.methodology.desc2': 'כדי לתרגם תפיסת עומק זו למיומנויות פרקטיות, אנו משלבים טכנולוגיה מתקדמת כאמצעי חווייתי. אנו עושים שימוש בסימולציות מיפוי רשת ובמשחקי חשיבה קוגניטיביים המשמשים כ"סימולטור טיסה" ניהולי. כלים אלו מאפשרים תרגול מעורר מעורבות של דינמיקות ארגוניות מורכבות בסביבה בטוחה ומבוססת נתונים.',
    'academy.methodology.bullet1': 'מודעות רשתית וראייה אסטרטגית',
    'academy.methodology.bullet2': 'רפלקציה חיה מבוססת נתונים',
    'academy.methodology.bullet3': 'יישום מיידי בסביבת העבודה',
    'academy.strategicSimulations': 'סימולציות אסטרטגיות',
    'academy.interactiveTraining': 'כלי אימון אינטראקטיבי',
    'academy.coreModules': 'סדנאות הליבה שלנו',
    'academy.developingPillars': 'תהליך מובנה ורציף לפיתוח ה-DNA הניהולי שלכם.',
    'academy.w1.title': '01. מבוא למנהיגות רשתית',
    'academy.w1.desc': 'מבוסס סימולציות מיפוי רשת. חשיפת המבנה הבלתי פורמלי של הארגון. המשתתפים לומדים כיצד לזהות מוקדי ידע, כוכבים סמויים וצווארי בקבוק המעכבים צמיחה.',
    'academy.w2.title': '02. השפעה ואומץ',
    'academy.w2.desc': 'מבוסס סימולציות מיפוי רשת. ניהול והשפעה ללא סמכות פורמלית. המשתתפים לומדים למנף את מיקומם ברשת כדי להוביל שינויים ולקדם יוזמות חוצות-ארגון.',
    'academy.w3.title': '03. אמון ובטחון פסיכולוגי',
    'academy.w3.desc': 'מבוסס סימולציות מיפוי רשת. מעבר מתפיסה מחלקתית לראייה מערכתית. שימוש בנתוני אמת כדי לגשר על נתקים מבניים ולייצר סינרגיה בין צוותים מבודדים.',
    'academy.w4.title': '04. הסתגלות לשינוי',
    'academy.w4.desc': 'מבוסס סימולציות משחקי חשיבה. התאמה לסביבה עסקית משתנה וקבלת החלטות בתנאי אי-ודאות. התנסות חווייתית בדילמות מורכבות הדורשות זיהוי הזדמנויות מהיר.',
    'academy.w5.title': '05. חשיבה יצירתית',
    'academy.w5.desc': 'מבוסס סימולציות משחקי חשיבה. מקסום תוצאות בסביבה של משאבים מוגבלים. תרגול בניית הסכמות, ניהול קונפליקטים ויצירת פתרונות Win-Win מורכבים.',
    'academy.w6.title': '06. קבלת החלטות',
    'academy.w6.desc': 'מבוסס סימולציות משחקי חשיבה. יצירת ביטחון פסיכולוגי בצוות. המחשה חווייתית של האופן שבו פעולות יחיד משפיעות על התוצאה והלכידות הקבוצתית.',
    'academy.upgradeDNA': 'שדרגו את ה-DNA הניהולי שלכם',
    'academy.upgradeDesc': 'ציידו את המנהלים שלכם בכישורים הנדרשים כדי לנווט בהצלחה בעולם רשתי.',
    'academy.bookWorkshop': 'הזמינו סדנה',

    // Leadership (דף מנהיגות / קטלוג סדנאות)
    'leadership.hero.title': 'פיתוח מיומנויות ומנהיגות רשתית',
    'leadership.hero.subtitle':
      "פיתוח מנהלים וצוותי מפתח באמצעות למידה חווייתית, סימולציות משחק ובניית 'תפיסת רשת' חוצת-ארגון. אנו מכינים את הטאלנטים של היום לאתגרי הניהול של עולם המחר, ומעניקים להם כלים פרקטיים להובלה והשפעה במציאות משתנה.",
    'leadership.hero.cta': 'לצפייה בקטלוג הסדנאות',
    'leadership.hero.imageAlt': 'סדנאות מנהיגות',
    'leadership.logosTitle': 'הסדנאות שלנו מניעות קדימה את הארגונים המובילים במשק',
    'leadership.catalog.title': 'קטלוג הסדנאות — Power Skills',
    'leadership.catalog.subtitle': 'מנהיגות רשתית ו-Power Skills — מותאמים לצוותי הנהלה ומפתחים',
    'leadership.cardFormat': '📍 פרונטלי | 💻 Online',
    'leadership.readMore': 'קרא עוד',
    'leadership.badge.networkMindset': 'Network Mindset',
    'leadership.badge.powerSkills': 'Power Skills',
    'leadership.workshop.1.title': 'פיתוח מנהיגות רשתית',
    'leadership.workshop.1.shortDesc':
      'המעבר מניהול היררכי לניהול רשתי, בניית חוסן ארגוני וגמישות מחשבתית. (כולל אבחון פרופיל אישי).',
    'leadership.workshop.1.syllabus':
      'בעולם שבו התרשים הארגוני כבר לא מספר את כל הסיפור, מנהלים נדרשים להוביל דרך רשתות. סדנה זו מקנה כלים פרקטיים למעבר מניהול היררכי נוקשה לניהול רשתי גמיש. נלמד כיצד למפות את הרשת הבלתי-פורמלית בארגון, לשבור סילוסים בין מחלקות, לזהות טאלנטים סמויים ומובילי דעה, ולבנות חוסן ארגוני שמאפשר לצוות להגיב מהר לשינויים.',
    'leadership.workshop.2.title': 'השפעה ואומץ ניהולי',
    'leadership.workshop.2.shortDesc':
      'איך משפיעים בארגון ומחוצה לו? כלים פרקטיים ליצירת השפעה ורשתות ככלי ניהולי.',
    'leadership.workshop.2.syllabus':
      'האתגר הגדול ביותר של מנהלי מטריצה ומובילי פרויקטים הוא הנעת תהליכים ללא סמכות ישירה. הסדנה חוקרת את נקודת ההשקה שבין השפעה לאומץ ניהולי. המשתתפים ירכשו כלי ניהול 360 מעלות, ילמדו כיצד למנף את הרשת הארגונית כדי להרחיב את מעגל ההשפעה שלהם, ויפתחו את האומץ הנדרש להובלת יוזמות מורכבות בסביבה פוליטית.',
    'leadership.workshop.3.title': 'בטחון פסיכולוגי ואמון',
    'leadership.workshop.3.shortDesc':
      'יצירת סביבה מקדמת ופרודוקטיבית, המאפשרת יצירת יחסים מיטיבים והובלת צוות.',
    'leadership.workshop.3.syllabus':
      'צוותים בעלי ביצועים גבוהים נשענים על תשתית של אמון, אך בתקופות לחץ ומשבר, הביטחון הפסיכולוגי נשחק במהירות. הסדנה מעניקה למנהלים פרקטיקות יומיומיות ליצירת סביבת עבודה בטוחה המעודדת לקיחת סיכונים מחושבים, העלאת רעיונות חדשים והודאה בטעויות. נבין כיצד חיבור אותנטי וניהול פגיע מניעים ישירות פרודוקטיביות וחדשנות.',
    'leadership.workshop.4.title': 'הסתגלות לשינוי וגמישות מחשבתית',
    'leadership.workshop.4.shortDesc':
      'פיתוח גמישות מחשבתית להתמודדות והסתגלות מהירה בעולם של אי-ודאות.',
    'leadership.workshop.4.syllabus':
      'במציאות עסקית תנודתית, היכולת להסתגל במהירות היא יתרון תחרותי קריטי. הסדנה צוללת אל מעבר לשינוי ההתנהגותי, ומתמקדת בפיתוח "שריר" הגמישות המחשבתית. מנהלים ילמדו כיצד לזהות ולהסיר חסמים קוגניטיביים לשינוי, לקבל החלטות גם כשהתנאים משתנים מול עיניהם, ולנהל את הגמישות של הצוות כולו תחת אי-ודאות.',
    'leadership.workshop.5.title': 'חשיבה יצירתית',
    'leadership.workshop.5.shortDesc':
      'ערעור על הנחות יסוד, הרחבת מרחב הפתרונות ושינוי דפוסי חשיבה שגרתיים.',
    'leadership.workshop.5.syllabus':
      'כשדרכי הפעולה השגרתיות מפסיקות לעבוד, מנהלים חייבים לדעת כיצד לחדש. באמצעות למידה מבוססת-משחק, סדנה זו מערערת על הנחות היסוד והאוטומטים המחשבתיים שלנו. המשתתפים יתרגלו טכניקות לפריצת "נעילות מחשבתיות", ירחיבו את מרחב הפתרונות לאתגרים מורכבים, ויסגלו דפוסי חשיבה יצירתיים שניתן ליישם מיד בעבודה השוטפת.',
    'leadership.workshop.6.title': 'קבלת החלטות',
    'leadership.workshop.6.shortDesc':
      'התמודדות עם תהליכי קבלת החלטות מורכבים והיכרות עם הטיות קוגניטיביות.',
    'leadership.workshop.6.syllabus':
      'מנהלים ניצבים מדי יום בפני זרם בלתי פוסק של החלטות, לרוב מתוך עודף רעשי רקע או חוסר במידע קריטי. הסדנה מפרקת את המנגנונים הפסיכולוגיים של תהליך קבלת ההחלטות וחושפת הטיות קוגניטיביות נפוצות שפוגעות בשיקול הדעת. המשתתפים ילמדו מודלים לסינון רעשים, שימוש נכון ב"חכמת ההמונים", וקבלת החלטות מהירות ומבוססות-נתונים תחת לחץ.',
    'leadership.tech.sectionTitle': 'הטכנולוגיה שמאחורי הסדנאות שלנו',
    'leadership.tech.ona.label': 'אינטליגנציה רשתית (ONA)',
    'leadership.tech.game.label': 'למידה מבוססת-משחק',
    'leadership.flexible.title': 'כשאי אפשר להיפגש פרונטלית: סדנאות Online אינטראקטיביות',
    'leadership.flexible.body':
      'כל תוכניות הפיתוח שלנו הותאמו במלואן להעברה מקוונת. בעזרת פלטפורמות המשחק והסימולציות הייחודיות שלנו, אנו מבטיחים חוויית למידה סוחפת שמשאירה את המשתתפים מחוברים ופעילים לאורך כל הסדנה, גם כשהם עובדים מהבית.',
    'leadership.flexible.imageCaption': 'צילום מסך — סדנת Zoom (מציין מיקום לתמונה)',
    'leadership.cta.title': 'בואו נבנה את ההכשרה המדויקת לצוות שלכם',
    'leadership.cta.button': 'לשיחת ייעוץ אישית',

    // About
    'about.mission': 'המשימה שלנו',
    'about.title': 'מומחים בניתוח ופיתוח רשתות ארגוניות.',
    'about.subtitle': 'אנו כאן כדי לקדם מעבר מתרשים ארגוני מסורתי לרשת עבודה אפקטיבית ושיתופית.',
    'about.orgChartDead': 'לחבר בין אנשים, לייצר ערך.',
    'about.longLiveNetwork': '',
    'about.story1': 'StepAhead הוקמה מתוך חזון לפתח טכנולוגיה חדשנית המבוססת על ניתוח רשתות כדי להעצים שיתופי פעולה ולחבר בין אנשים.',
    'about.story2': 'במשך למעלה ממאה שנה, ארגונים נוהלו כמו מכונות: מלמעלה למטה, בסיילואים, ובנוקשות מחשבתית. אבל העולם השתנה. העבודה כיום היא מורכבת, שיתופית ומהירה.',
    'about.story3': 'שילבנו את המדע של ניתוח רשתות ארגוניות (ONA) יחד עם כלי מנהיגות פרקטיים כדי לתת למנהלים משקפיים חדשים—כאלה שמאפשרים לראות את הזרימה האמיתית של אמון, מידע וחדשנות.',
    'about.whatDrivesUs': 'מה מניע אותנו',
    'about.drive1Title': 'חיבור בין אנשים',
    'about.drive1Desc': 'אנחנו מאמינים בכוחו של הקשר האנושי. המטרה שלנו היא לבנות אמון, לעודד שיתופי פעולה אמיתיים ולחבר בין אנשים מעבר לגבולות הארגון.',
    'about.drive2Title': 'טכנולוגיה חדשנית',
    'about.drive2Desc': 'תחושת בטן היא חשובה, אבל אי אפשר להתווכח עם דאטה. אנו משתמשים בטכנולוגיית ONA מתקדמת כדי למפות את הבלתי-נראה ולהפוך דינמיקות חברתיות לתובנות ברורות.',
    'about.drive3Title': 'החשיבה הרשתית',
    'about.drive3Desc': 'אנחנו נלהבים לעזור למנהלים לעשות את המעבר מהיררכיה נוקשה של "פקודה ושליטה" למנהיגות רשתית המבוססת על השפעה וגמישות.',
    'about.meetLeadership': 'הצוות המוביל',
    'about.sharonRole': 'מייסדת ומנכ"לית תפעול (COO)',
    'about.sharonBio': "מומחית לדינמיקה ארגונית ופתרון קונפליקטים. כבעלים של 'גומא-גבים', המרכז המוביל בישראל לגישור ואימון, שרון דואגת שהטכנולוגיה שלנו תשרת את האנשים, ומתרגמת נתוני רשת לאסטרטגיות בניית אמון בשטח.",
    'about.yuvalRole': 'יועץ אקדמי',
    'about.yuvalBio': 'סמכות עולמית בחקר רשתות חברתיות וארגוניות. ראש תחום מנהיגות ורשתות בבית הספר לניהול WHU, גרמניה. יובל מספק את התשתית המדעית והמתודולוגית לאלגוריתמים של StepAhead.',
    'about.nadavRole': 'מנכ"ל',
    'about.nadavBio': "חלוץ בתחום הלמידה מבוססת-משחק (GBL) והערכת כישורים. עם רקע כמרצה לחשיבה אסטרטגית ומומחה EdTech, נדב מוביל את חזון 'הארגון מבוסס-הכישורים', תוך התמקדות בחשיפת טאלנטים נסתרים דרך טכנולוגיה.",
    'about.joinRevolution': 'מוכנים לעשות את הצעד הבא?',
    'about.revolutionDesc': 'בין אם אתם ארגון שמחפש להתפתח או שותפים לדרך, נשמח להכיר.',
    'about.contactUs': 'צרו קשר',

    // Team
    'team.nadav.name': 'נדב אגוזי',
    'team.nadav.title': 'מנכ"ל',
    'team.nadav.bio': 'חלוץ בתחום האבחון ופיתוח מיומנויות מבוססי-משחק. עם רקע כמרצה לחשיבה אסטרטגית ומומחה אד-טק, נדב מוביל את החזון של "הארגון מבוסס-הכישורים", ומתמקד בחשיפת כישרונות חבויים באמצעות טכנולוגיה.',
    'team.sharon.name': 'שרון רנדליך',
    'team.sharon.title': 'מייסדת וסמנכ"לית תפעול',
    'team.sharon.bio': 'מומחית לדינמיקה ארגונית ויישוב סכסוכים. כבעלים של "גומא-גבים", מרכז הגישור המוביל בישראל, שרון מבטיחה שהטכנולוגיה שלנו משרתת את האנשים, ומתרגמת נתוני רשת לאסטרטגיות פעולה הבונות אמון.',

    // Contact Form
    'contact.form.title': 'שלחו לנו הודעה',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'אימייל עבודה',
    'contact.form.company': 'שם חברה',
    'contact.form.message': 'איך נוכל לעזור?',
    'contact.form.submit': 'שליחת הודעה',

    // CTA
    'cta.title': 'מוכנים לממש את הפוטנציאל הרשתי שלכם?',
    'cta.description': 'גלו את הדפוסים הנסתרים של שיתוף פעולה ומנהיגות בארגון שלכם.',
    'cta.button': 'קבעו הדגמה',
    'cta.badge': 'פיתוח רשתות',

    // Footer
    'footer.tagline': 'מומחים בניתוח ופיתוח רשתות ארגוניות. מעבר מתרשים ארגוני מסורתי לרשת עבודה אפקטיבית ושיתופית.',
    'footer.solutionsHeading': 'פתרונות',
    'footer.networkLeadership': 'תוכניות מנהיגות רשתית',
    'footer.collaborationIntelligence': 'פיתוח רשתות',
    'footer.talentSelection': 'איתור והערכת טאלנטים',
    'footer.collabAgent': 'Collab Agent (בטא)',
    'footer.company': 'החברה',
    'footer.aboutUs': 'אודותינו',
    'footer.contact': 'צור קשר',
    'footer.contactUs': 'צור קשר',
    'footer.followLinkedIn': 'עקבו אחרינו ב-LinkedIn',
    'footer.location': 'תל אביב, ישראל',
    'footer.globalOps': 'פעילות גלובלית',
    'footer.rights': 'כל הזכויות שמורות.',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    'footer.legal': 'משפטי',
    'footer.cookieBanner':
      'אנו משתמשים בעוגיות כדי לשפר את החוויה ולנתח תנועה באתר. המשך השימוש באתר מהווה הסכמה לשימוש בעוגיות ול',
    'footer.cookieAccept': 'אישור',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
