import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.aboutUs': 'About Us',
    'nav.platform': 'Platform',
    'nav.solutions': 'Solutions',
    'nav.solutionsDropdown': 'Solutions',
    'nav.talentAcquisition': 'Talent Acquisition',
    'nav.leadershipInnovation': 'Leadership & Innovation',
    'nav.organizationalDynamics': 'Organizational Dynamics',
    'nav.networkSkillsLeadership': 'Network Leadership Programs',
    'nav.collaborationAnalytics': 'The ONA Platform',
    'nav.talentSelection': 'Talent Selection & Assessment',
    'nav.methodology': 'Methodology',
    'nav.aiLabs': 'Collab Agent',
    'nav.academy': 'Academy',
    'nav.process': 'Our Process',
    'nav.skills': 'Network Skills',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.cta': "Let's Talk",

    // Hero (new value proposition)
    'hero.title': 'Network Leadership',
    'hero.subtitle': 'Unlocking the full potential of the Skills-Based Organization',
    'hero.mainTitle': 'Build a Connected, Future-Ready Organization',
    'hero.mainTitleLine1': 'Build a Connected,',
    'hero.mainTitleLine2': 'Future-Ready Organization',
    'hero.mainSubtitle': 'A winning organization is built on its people and how they connect. Use our data-driven tools to empower agile leaders, break down silos, and accelerate organizational innovation.',
    'hero.exploreSolutions': 'Explore Our Solutions',
    'hero.cta': 'Book a Consultation',
    'hero.cta2': 'Our Process',
    'hero.activateNetwork': 'Activate Your Network',
    'hero.meetAgent': 'Meet the Collab Agent',
    'hero.trustedBy': 'Trusted by',
    'hero.trustedBySubtitle': 'Trusted by Forward-Thinking Organizations',

    // Homepage - The 3 Solutions
    'index.pillar1.title': 'Network Leadership Programs',
    'index.pillar1.text': 'Train managers on how to build relationships, connect the right people, and lead effectively across teams without relying on formal authority.',
    'index.pillar1.benefit1': 'Identify hidden bottlenecks',
    'index.pillar1.benefit2': 'Cultivate high-trust relationships',
    'index.pillar1.benefit3': 'Accelerate cross-functional alignment',
    'index.pillar1.button': 'Explore Leadership Programs',
    'index.pillar2.title': 'Collaboration Intelligence',
    'index.pillar2.text': 'Advanced network mapping tools that show you exactly how your teams actually work together to identify bottlenecks and reveal hidden talent.',
    'index.pillar2.button': 'Discover ONA Platform',
    'index.pillar3.title': 'Talent Selection & Assessment',
    'index.pillar3.text': 'Data-driven, game-based cognitive assessments to evaluate and hire candidates who have the right skills to integrate into your network.',
    'index.pillar3.button': 'Discover Talent Tools',

    // Homepage - Our Methodology
    'index.philosophy.title': 'The Org Chart is a Myth. The Network is Reality.',
    'index.philosophy.text': 'Value is no longer created in silos—it flows through invisible networks. We provide the methodology and tools to transition your company from a rigid hierarchy into an agile, connected ecosystem.',

    // Homepage - The Future (AI Collab Agent)
    'index.future.title': 'Meet Your Collab Agent (Beta)',
    'index.future.text': 'The right person is already in your contacts. Tell us what you\'re working on — and we\'ll find the exact people who can help you right now. Not the obvious ones. The ones you forgot you knew. Our AI agent sits directly in your workflow to help you leverage your existing network effectively and connect you with the right people at the right time.',
    'index.future.badge': 'AI Labs',
    'index.future.cta': 'Join the Waitlist',
    'index.future.ctaAlt': 'Become a Design Partner',

    // Myth Section
    'myth.title': 'The Org Chart is a Myth',
    'myth.subtitle': 'The Network is Reality',
    'myth.description': 'Value is no longer created in silos — it flows through invisible networks. We help you see, understand, and optimize these hidden connections.',

    // Process
    'process.title': 'From Hidden Data to Organizational Impact',
    'process.subtitle': 'The 4-Step Process',
    'process.step1.title': 'Identify',
    'process.step1.subtitle': 'Mapping',
    'process.step1.desc': 'Find your "Invisible Heroes" — the most connected and influential people based on actual collaboration data.',
    'process.step2.title': 'Diagnose',
    'process.step2.subtitle': 'Profiling',
    'process.step2.desc': 'Assess specific relational skills: ability to build trust, exert influence, and bridge disparate groups.',
    'process.step3.title': 'Developing',
    'process.step3.subtitle': 'Skills',
    'process.step3.desc': 'Targeted development programs to strengthen network leadership capabilities.',
    'process.step4.title': 'Implementing',
    'process.step4.subtitle': 'AI Agent',
    'process.step4.desc': 'AI-powered coaching and real-time connectivity insights for continuous improvement.',

    // Skills
    'skills.title': 'The Network Mindset',
    'skills.subtitle': 'Essential Skills for the Agile Era',
    'skills.hub.title': 'Network Hub',
    'skills.hub.desc': 'A person at the center of conversations, sought for advice and guidance. Builds high-trust relationships.',
    'skills.bridge.title': 'Strategic Bridge',
    'skills.bridge.desc': 'Connects between units, ranks, and different fields of expertise. Facilitates alignment and balance.',
    'skills.gardener.title': 'Network Gardener',
    'skills.gardener.desc': 'Maintains deep, local, continuous relationships. Strengthens high-quality relationships.',
    'skills.pioneer.title': 'Network Pioneer',
    'skills.pioneer.desc': 'Constantly searches for new connections and domains. Builds high-diversity relationships.',

    // Index
    'index.turnOrgChart': 'Turn Your Org Chart Into a Living Network',
    'index.orgChartDesc': 'Move beyond static hierarchies. We use Organizational Network Analysis (ONA) to reveal how work really gets done.',
    'index.innovation': 'Innovation & Silo Busting',
    'index.innovationDesc': 'Innovation happens at the intersection. We visualize structural holes and bridge disconnected silos to speed up ideation.',
    'index.retention': 'Retention & Burnout',
    'index.retentionDesc': 'Spot flight risks before they resign. Visualize isolated nodes (purple) vs. embedded employees to predict attrition.',
    'index.leadership': 'Network Leadership',
    'index.leadershipDesc': 'Shift from hierarchy to hub. Identify and train your central connectors to influence change and drive strategy.',
    'index.howWeDoIt': 'How We Do It',
    'index.explorePlatform': 'Explore The Platform',
    'index.risk': 'Risk',

    // Platform
    'platform.os': 'The Platform',
    'platform.title': 'Visualize the Network. Unlock True Collaboration.',
    'platform.subtitle': "We use advanced Organizational Network Analysis (ONA) to reveal your company's hidden connections, combined with an AI assistant that empowers every employee to leverage them.",
    'platform.onaEngine': 'Organizational Network Analysis (ONA)',
    'platform.visualizeInvisible': 'Map the Reality',
    'platform.onaDesc': 'We map the actual structure and flow of your organization. Our engine identifies systemic bottlenecks, isolated talent, and hidden influencers, giving leadership a clear picture of how work actually gets done.',
    'platform.onaFeature1': 'Visualize cross-functional communication flows',
    'platform.onaFeature2': 'Identify organizational bottlenecks and silos',
    'platform.onaFeature3': 'Track overall network health and integration',
    'platform.collabAgent': 'Smart Connections',
    'platform.actionableNudges': 'On-Demand Collaboration',
    'platform.agentDesc': "We shift the power directly to your employees and managers. The Collab Agent lives in their daily workflow (Teams/Slack), analyzing their immediate challenges and suggesting the exact right people to connect with to solve them.",
    'platform.agentFeature1': 'Real-time connection recommendations',
    'platform.agentFeature2': 'Based on actual organizational needs and ONA data',
    'platform.agentFeature3': 'Seamless integration into daily workflows',
    'platform.networkProfiling': 'Network Skill Development',
    'platform.deepInsight': 'Cultivate the Mindset',
    'platform.profilingDesc': 'Beyond just introductions, the platform helps employees understand and develop their unique "Network Persona." It provides continuous profiling and coaching to build stronger, more effective collaborative skills.',
    'platform.profilingFeature1': 'Discover personal network strengths and blind spots',
    'platform.profilingFeature2': 'Targeted coaching for network skill development',
    'platform.profilingFeature3': 'Empower managers to build high-trust teams',
    'platform.seeHowItWorks': 'See How It Works',
    'platform.readyTransform': 'Ready to Transform Your Organization?',
    'platform.joinCompanies': 'Join the forward-thinking companies already using StepAhead.',
    'platform.bookDemo': 'Book a Demo',
    'platform.contactSales': 'Contact Sales',

    // Solutions
    'solutions.badge': 'SOLUTIONS FOR EVERY CHALLENGE',
    'solutions.title': 'Solving the Complexity of Modern Work',
    'solutions.subtitle': 'From breaking down silos to navigating complex organizational changes—we turn your biggest human challenges into manageable data insights.',
    'solutions.siloBusting': 'Silo Busting & Collaboration',
    'solutions.siloDesc': 'Organizations lose millions on disconnected departments. We identify communication breaks in real-time and nudge leaders to bridge the gaps instantly.',
    'solutions.siloBenefit1': 'Increase cross-functional innovation',
    'solutions.siloBenefit2': 'Reduce duplication of work',
    'solutions.siloBenefit3': 'Speed up decision making',
    'solutions.changeManagement': 'Change Management',
    'solutions.changeDesc': "Whether it's M&A, hyper-growth, or restructuring—change fails due to people dynamics. We map the network to identify key 'Change Agents' who can accelerate adoption and integration.",
    'solutions.changeBenefit1': 'Accelerate M&A integration',
    'solutions.changeBenefit2': 'Manage rapid growth pains',
    'solutions.changeBenefit3': 'Identify cultural blockers',
    'solutions.talentRetention': 'Talent Retention & Burnout',
    'solutions.retentionDesc': 'Spot flight risks before they resign. Our AI analyzes communication patterns to detect burnout (over-collaboration) and isolation (disengagement) early.',
    'solutions.retentionBenefit1': 'Predict burnout risk',
    'solutions.retentionBenefit2': 'Identify isolated high-performers',
    'solutions.retentionBenefit3': 'Improve manager-employee connection',
    'solutions.leadershipDev': 'Network Leadership Development',
    'solutions.leadershipDesc': "Hierarchy is dead. We measure and train managers on how to become 'Hubs' of trust and influence, using data-driven insights and gamified simulations.",
    'solutions.leadershipBenefit1': 'Move from command to connect',
    'solutions.leadershipBenefit2': 'Visualize leadership impact',
    'solutions.leadershipBenefit3': 'Data-driven coaching plans',
    'solutions.seeHowItWorks': 'See How It Works',
    'solutions.dontSlowDown': "Don't let invisible problems slow you down",
    'solutions.getStrategy': 'Get a Strategy Session',

    // Assessment
    'assessment.badge': 'AI-SUPPORTED TALENT ASSESSMENT',
    'assessment.title': 'Game-Based Assessments for the Modern Workforce',
    'assessment.subtitle': 'Replace long, tiresome questionnaires with fast, engaging critical thinking games. We track authentic behavioral responses to give you exclusive insights into your candidates\' true potential.',
    'assessment.whyGames': 'THE EXPERIENCE',
    'assessment.whyGamesTitle': 'Authentic Behavior, Not Rehearsed Answers',
    'assessment.whyGamesDesc': 'While candidates play, our advanced algorithms evaluate their cognitive processes in real-time. This provides a positive differentiation for your employer brand while generating a multidimensional skill profile free from interview bias.',
    'assessment.feature1': 'No prior knowledge or instruction required',
    'assessment.feature2': 'Accessible 24/7 from any mobile or desktop device',
    'assessment.feature3': 'Provides a positive, innovative candidate experience',
    'assessment.processTitle': 'The 4-Step Assessment Process',
    'assessment.step1Title': '1. Build the Journey',
    'assessment.step1Desc': 'Create a customized test with flexible game types tailored to the specific skills required for the role.',
    'assessment.step2Title': '2. Send the Link',
    'assessment.step2Desc': 'Send a personalized link for easy registration and access. No monitor presence or installation required.',
    'assessment.step3Title': '3. Game-Based Test',
    'assessment.step3Desc': 'Candidates experience an immersive, fun challenge that tracks their actual problem-solving in real-time.',
    'assessment.step4Title': '4. Advanced AI Reports',
    'assessment.step4Desc': 'Get an instant ranking of all candidates with AI-assisted analysis highlighting skill gaps and strengths.',
    'assessment.skillsTitle': 'Skills & Abilities Measured',
    'assessment.skill1': 'Solving Complex Problems',
    'assessment.skill1Desc': 'Analyzing data and executing solutions under pressure.',
    'assessment.skill2': 'Pattern Recognition',
    'assessment.skill2Desc': 'Identifying trends and rules in shifting, dynamic environments.',
    'assessment.skill3': 'Resourcefulness & Initiative',
    'assessment.skill3Desc': 'Maximizing limited resources and identifying hidden opportunities.',
    'assessment.ctaTitle': 'Ready to transform your hiring?',
    'assessment.ctaDesc': 'Get a comprehensive skill profile compared to global benchmarks for every candidate.',
    'assessment.ctaButton': 'Book a Platform Demo',

    // Academy
    'academy.badge': 'PRACTICAL LEADERSHIP WORKSHOPS',
    'academy.title': 'Network Leadership Academy',
    'academy.subtitle': 'Practical workshops for the new era of management. We help leaders shift from a hierarchical mindset to a networked one, using advanced simulations and practical tools.',
    'academy.downloadSyllabus': 'Download Syllabus',
    'academy.methodology': 'THE METHODOLOGY',
    'academy.theoryMeetsPractice': 'Experiential, Data-Driven Learning',
    'academy.methodologyDesc1': 'Network concepts can be abstract. To bridge the gap, we use advanced game simulations as a training aid. Think of it as a "Flight Simulator" for management.',
    'academy.methodologyDesc2': 'The games aren\'t the goal—they are the means to practice complex dynamics like resource allocation, negotiation, and collaboration in a risk-free environment.',
    'academy.methodologyFeature1': 'Active experimentation',
    'academy.methodologyFeature2': 'Immediate feedback loops',
    'academy.methodologyFeature3': 'Real-world analogy analysis',
    'academy.strategicSimulations': 'Strategic Simulations',
    'academy.interactiveTraining': 'Interactive Training Aid',
    'academy.coreModules': 'The 6-Step Leadership Journey',
    'academy.developingPillars': 'A structured, sequential process to develop your management DNA.',
    'academy.module1Title': '01. Intro to Network Leadership',
    'academy.module1Desc': 'Shifting from hierarchical thinking to network awareness. Learn how to map your connections, build trust, and maintain relationships across silos.',
    'academy.module2Title': '02. Influence & Courage',
    'academy.module2Desc': 'How to influence without formal authority. Learn to leverage organizational networks to drive change and exercise managerial courage.',
    'academy.module3Title': '03. Trust & Psychological Safety',
    'academy.module3Desc': 'The human core of networks. Practical tools for building environments where authentic connection and productive collaboration thrive.',
    'academy.module4Title': '04. Adaptability to Change',
    'academy.module4Desc': 'Developing cognitive and behavioral flexibility. Learn to make rapid decisions under uncertainty and overcome the "unfair advantage" in shifting realities.',
    'academy.module5Title': '05. Creative Thinking',
    'academy.module5Desc': 'Break out of habitual thinking patterns. Use your network to challenge core assumptions, expand your solution space, and drive innovation.',
    'academy.module6Title': '06. Decision Making',
    'academy.module6Desc': 'Balance initiative and responsiveness. Master complex resource management and understand how groups make decisions within the network.',
    'academy.upgradeDNA': 'Upgrade Your Management DNA',
    'academy.upgradeDesc': 'Equip your leaders with the skills they need to navigate a networked world.',
    'academy.bookWorkshop': 'Book a Workshop',

    // About
    'about.mission': 'OUR MISSION',
    'about.title': 'Architects of the Networked Organization',
    'about.subtitle': 'We exist to transform static hierarchies into living, breathing, adaptive networks of shared value.',
    'about.orgChartDead': 'Connect People, Create Value.',
    'about.longLiveNetwork': '',
    'about.story1': 'StepAhead was founded with the vision of developing innovative technology based on network analysis to enable collaboration and connect people.',
    'about.story2': 'For over a century, organizations were managed like machines: top-down, siloed, and rigid. But the world has changed. Work today is complex, collaborative, and fast-paced.',
    'about.story3': 'We combined the science of Organizational Network Analysis (ONA) with practical leadership tools to give leaders a new pair of glasses—ones that see the actual flow of trust, information, and innovation.',
    'about.whatDrivesUs': 'What Drives Us',
    'about.drive1Title': 'Connecting People',
    'about.drive1Desc': 'We believe in the power of human connection. We exist to build trust, foster genuine collaboration, and bring people together across organizational boundaries.',
    'about.drive2Title': 'Innovative Technology',
    'about.drive2Desc': 'Gut feeling is important, but data is undeniable. We use advanced Network Analysis (ONA) to map the invisible and turn complex social dynamics into clear insights.',
    'about.drive3Title': 'The Network Mindset',
    'about.drive3Desc': 'We are passionate about guiding leaders away from rigid, command-and-control hierarchies and towards agile, influence-based network leadership.',
    'about.meetLeadership': 'Meet the Leadership',
    'about.sharonRole': 'Founder & COO',
    'about.sharonBio': "An expert in organizational dynamics and conflict resolution. As the owner of 'Gome-Gevim', Israel's leading mediation center, Sharon ensures our technology serves the people, translating network data into actionable strategies that build trust.",
    'about.yuvalRole': 'Academic Advisor',
    'about.yuvalBio': 'A world-renowned authority on Network Theory. Chair of Leadership and Networks at WHU School of Management, Germany. Yuval provides the scientific backbone to our ONA algorithms and methodology.',
    'about.nadavRole': 'CEO',
    'about.nadavBio': "A pioneer in game-based assessment and skill development. With a background as a strategic thinking lecturer and EdTech expert, Nadav leads the vision of the 'Skills-Based Organization', focusing on uncovering hidden talent through technology.",
    'about.joinRevolution': 'Join the Revolution',
    'about.revolutionDesc': "Whether you are an organization looking to evolve or a partner looking to collaborate, we'd love to connect.",
    'about.contactUs': 'Contact Us',

    // CTA
    'cta.title': 'Ready to Unlock Your Network Potential?',
    'cta.description': 'Discover the hidden patterns of collaboration and leadership within your organization.',
    'cta.button': 'Schedule a Demo',

    // Footer
    'footer.tagline': 'Architects of the Networked Organization. We transform static hierarchies into adaptive, data-driven human networks.',
    'footer.solutionsHeading': 'Solutions',
    'footer.networkLeadership': 'Network Leadership Programs',
    'footer.collaborationIntelligence': 'Collaboration Intelligence',
    'footer.talentSelection': 'Talent Selection & Assessment',
    'footer.collabAgent': 'Collab Agent (Beta)',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.contactUs': 'Contact Us',
    'footer.followLinkedIn': 'Follow us on LinkedIn',
    'footer.location': 'Tel Aviv, Israel',
    'footer.globalOps': 'Global Operations',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.about': 'אודותינו',
    'nav.aboutUs': 'אודותינו',
    'nav.platform': 'פלטפורמה',
    'nav.solutions': 'פתרונות',
    'nav.solutionsDropdown': 'פתרונות',
    'nav.talentAcquisition': 'גיוס טאלנטים',
    'nav.leadershipInnovation': 'מנהיגות וחדשנות',
    'nav.organizationalDynamics': 'דינמיקה ארגונית',
    'nav.networkSkillsLeadership': 'תוכניות מנהיגות רשתית',
    'nav.collaborationAnalytics': 'פלטפורמת ONA',
    'nav.talentSelection': 'איתור והערכת טאלנטים',
    'nav.methodology': 'מתודולוגיה',
    'nav.aiLabs': 'Collab Agent',
    'nav.academy': 'אקדמיה',
    'nav.process': 'התהליך שלנו',
    'nav.skills': 'כישורי רשת',
    'nav.contact': 'צור קשר',
    'nav.getStarted': 'התחילו עכשיו',
    'nav.cta': 'דברו איתנו',

    // Hero
    'hero.title': 'מנהיגות רשתית',
    'hero.subtitle': 'מימוש מלוא הפוטנציאל של הארגון מבוסס-הכישורים',
    'hero.mainTitle': 'לבנות ארגון מחובר שמוכן לאתגרי המחר',
    'hero.mainTitleLine1': 'לבנות ארגון מחובר',
    'hero.mainTitleLine2': 'שמוכן לאתגרי המחר',
    'hero.mainSubtitle': 'הדרך לארגון מנצח עוברת באנשים שלו ובאופן שבו הם מחוברים. השתמשו בכלים מבוססי הנתונים שלנו כדי לחזק מנהיגים אג\'יליים, לפרק סיילואים, ולהאיץ חדשנות ארגונית.',
    'hero.exploreSolutions': 'גלו את הפתרונות שלנו',
    'hero.cta': 'קבעו שיחת ייעוץ',
    'hero.cta2': 'התהליך שלנו',
    'hero.activateNetwork': 'מנפו את הרשת שלכם',
    'hero.meetAgent': 'הכירו את Collab Agent',
    'hero.trustedBy': 'סומכים עלינו',
    'hero.trustedBySubtitle': 'ארגונים מובילים שסומכים עלינו',

    // Homepage - The 3 Solutions
    'index.pillar1.title': 'תוכניות מנהיגות רשתית',
    'index.pillar1.text': 'הכשרת מנהלים לבניית מערכות יחסים, חיבור האנשים הנכונים והובלה אפקטיבית בין צוותים - מתוך השפעה, וללא הסתמכות על סמכות פורמלית בלבד.',
    'index.pillar1.benefit1': 'זיהוי צווארי בקבוק נסתרים',
    'index.pillar1.benefit2': 'טיפוח יחסי אמון גבוהים',
    'index.pillar1.benefit3': 'האצת ממשקי עבודה חוצי-ארגון',
    'index.pillar1.button': 'גלו תוכניות מנהיגות',
    'index.pillar2.title': 'פלטפורמת ONA',
    'index.pillar2.text': 'כלי מיפוי רשת מתקדמים שמראים בדיוק איך הצוותים והמחלקות שלכם עובדים יחד בפועל – כדי לזהות צווארי בקבוק ולחשוף טאלנטים נסתרים.',
    'index.pillar2.button': 'גלו את פלטפורמת ONA',
    'index.pillar3.title': 'איתור והערכת טאלנטים',
    'index.pillar3.text': 'הערכות קוגניטיביות מבוססות-משחק לזיהוי מועמדים עם הכישורים והפוטנציאל להשתלב ברשת הארגונית שלכם.',
    'index.pillar3.button': 'גלו כלי הערכה',

    // Homepage - Our Methodology
    'index.philosophy.title': 'העץ הארגוני הוא מיתוס. הרשת היא המציאות.',
    'index.philosophy.text': 'ערך כבר לא נוצר בממגורות — הוא זורם דרך רשתות בלתי נראות. אנו מספקים את המתודולוגיה והכלים להעביר את החברה שלכם מהיררכיה נוקשה למערכת אקולוגית אג\'ילית ומחוברת.',

    // Homepage - The Future (AI Collab Agent)
    'index.future.title': 'הכירו את Collab Agent (בטא)',
    'index.future.text': 'האדם הנכון כבר נמצא בארגון שלכם. ספרו לנו מול איזה אתגר אתם עומדים — ואנו נמצא את האנשים המדויקים שיכולים לעזור לכם עכשיו. לא רק המובנים מאליהם, אלא אלה ששכחתם שאתם מכירים. סוכן ה-AI שלנו משתלב ישירות בסביבת העבודה היומיומית שלכם (Teams/Slack) כדי לחבר אתכם לאנשים הנכונים בזמן הנכון.',
    'index.future.badge': 'AI Labs',
    'index.future.cta': 'הצטרפו לרשימת ההמתנה',
    'index.future.ctaAlt': 'הפכו לשותף עיצוב (Design Partner)',

    // Myth Section
    'myth.title': 'העץ הארגוני הוא מיתוס',
    'myth.subtitle': 'הרשת היא המציאות',
    'myth.description': 'ערך כבר לא נוצר בממגורות — הוא זורם דרך רשתות בלתי נראות. אנחנו עוזרים לכם לראות, להבין ולייעל את הקשרים הנסתרים האלה.',

    // Process
    'process.title': 'מנתונים נסתרים להשפעה ארגונית',
    'process.subtitle': 'תהליך 4 השלבים',
    'process.step1.title': 'זיהוי',
    'process.step1.subtitle': 'מיפוי',
    'process.step1.desc': 'מצאו את ה"גיבורים הנסתרים" — האנשים המחוברים והמשפיעים ביותר על בסיס נתוני שיתוף פעולה אמיתיים.',
    'process.step2.title': 'אבחון',
    'process.step2.subtitle': 'אפיון רשתי',
    'process.step2.desc': 'הערכת כישורים יחסיים ספציפיים: היכולת לבנות אמון, לייצר השפעה ולגשר בין קבוצות.',
    'process.step3.title': 'פיתוח',
    'process.step3.subtitle': 'כישורים',
    'process.step3.desc': 'תוכניות פיתוח ממוקדות לחיזוק יכולות מנהיגות רשתית.',
    'process.step4.title': 'יישום',
    'process.step4.subtitle': 'סוכן AI',
    'process.step4.desc': 'ליווי אישי מבוסס AI ותובנות קישוריות בזמן אמת לשיפור מתמיד.',

    // Skills
    'skills.title': 'החשיבה הרשתית',
    'skills.subtitle': 'כישורים חיוניים לעידן האג\'ילי',
    'skills.hub.title': 'צומת מרכזי (Hub)',
    'skills.hub.desc': 'אדם במרכז השיחות, אליו פונים לייעוץ והדרכה. בונה יחסי אמון גבוהים.',
    'skills.bridge.title': 'מגשר אסטרטגי',
    'skills.bridge.desc': 'מחבר בין יחידות, דרגים ותחומי מומחיות שונים. מאפשר סנכרון ואיזון.',
    'skills.gardener.title': 'מטפח רשת (Gardener)',
    'skills.gardener.desc': 'מקיים קשרים עמוקים, מקומיים ורציפים. מחזק מערכות יחסים איכותיות.',
    'skills.pioneer.title': 'חלוץ רשת (Pioneer)',
    'skills.pioneer.desc': 'מחפש כל הזמן קשרים ותחומים חדשים. בונה רשת בעלת גיוון גבוה.',

    // Index
    'index.turnOrgChart': 'הפכו את העץ הארגוני לרשת דינמית',
    'index.orgChartDesc': 'התקדמו מעבר להיררכיה הסטטית. אנו משתמשים בניתוח רשתות ארגוניות (ONA) כדי לחשוף איך העבודה באמת מתבצעת.',
    'index.innovation': 'מהירות וחדשנות',
    'index.innovationDesc': 'חדשנות קורית בנקודות החיבור. המערכת מזהה "חורים ברשת" (Structural Holes) ומגשרת בין מחלקות מבודדות כדי להאיץ תהליכי עבודה ויצירתיות.',
    'index.retention': 'שימור טאלנטים',
    'index.retentionDesc': 'זהו עובדים מבודדים לפני שהם עוזבים. ניתוח רשתי מתקדם לחיזוי סיכוני עזיבה ושחיקה.',
    'index.leadership': 'מנהיגות מודרנית',
    'index.leadershipDesc': 'מנהלים לומדים להשפיע דרך אמון וחיבורים (Hubs), ולא רק מתוקף סמכותם.',
    'index.howWeDoIt': 'איך אנחנו עושים את זה',
    'index.explorePlatform': 'גלו את הפלטפורמה',
    'index.risk': 'ניהול סיכונים',

    // Platform
    'platform.os': 'הפלטפורמה שלנו',
    'platform.title': 'להפוך את הרשת לגלויה. לממש את פוטנציאל הארגון.',
    'platform.subtitle': 'אנו משתמשים בניתוח רשתות ארגוניות (ONA) מתקדם כדי לחשוף את הקשרים הנסתרים של החברה שלכם, יחד עם סוכן AI שמעצים כל עובד לנצל אותם.',
    'platform.onaEngine': 'ניתוח רשתות ארגוניות (ONA)',
    'platform.visualizeInvisible': 'למפות את המציאות',
    'platform.onaDesc': 'אנו ממפים את המבנה והזרימה האמיתיים של הארגון. המערכת מזהה צווארי בקבוק מערכתיים, טאלנטים מבודדים ומוקדי השפעה, ומעניקה להנהלה תמונה ברורה של איך העבודה באמת מתבצעת.',
    'platform.onaFeature1': 'ויזואליזציה של זרימת מידע חוצת-ארגון',
    'platform.onaFeature2': 'זיהוי צווארי בקבוק וסיילואים',
    'platform.onaFeature3': 'מעקב אחר בריאות ואינטגרציית הרשת',
    'platform.collabAgent': 'חיבורים חכמים',
    'platform.actionableNudges': 'שיתוף פעולה לפי דרישה',
    'platform.agentDesc': 'אנו מעבירים את הכוח ישירות לעובדים ולמנהלים. הסוכן חי בסביבת העבודה היומיומית שלהם (Teams/Slack), מנתח את האתגרים המיידיים ומציע את האנשים הנכונים לחיבור.',
    'platform.agentFeature1': 'המלצות לחיבורים בזמן אמת',
    'platform.agentFeature2': 'מבוסס על צרכים ארגוניים ונתוני ONA',
    'platform.agentFeature3': 'אינטגרציה חלקה ליום העבודה',
    'platform.networkProfiling': 'פיתוח כישורי רשת',
    'platform.deepInsight': 'טיפוח החשיבה הרשתית',
    'platform.profilingDesc': 'הפלטפורמה עוזרת לעובדים להבין ולפתח את ה"פרסונה הרשתית" הייחודית שלהם. דרך פרופילינג וליווי מתמשך, אנו בונים כישורי עבודה משותפת חזקים ואפקטיביים יותר.',
    'platform.profilingFeature1': 'גילוי חוזקות ונקודות עיוורון ברשת האישית',
    'platform.profilingFeature2': 'אימון ממוקד לפיתוח כישורי רשת',
    'platform.profilingFeature3': 'העצמת מנהלים לבניית צוותי אמון',
    'platform.seeHowItWorks': 'ראו איך זה עובד',
    'platform.readyTransform': 'מוכנים להפוך לארגון רשתי?',
    'platform.joinCompanies': 'הצטרפו לארגונים החדשניים שכבר משתמשים ב-StepAhead.',
    'platform.bookDemo': 'קבעו הדגמה',
    'platform.contactSales': 'דברו עם צוות המכירות',

    // Solutions
    'solutions.badge': 'פתרונות לכל אתגר ארגוני',
    'solutions.title': 'פתרונות לארגונים בצמיחה ושינוי',
    'solutions.subtitle': 'אנו הופכים את האתגרים האנושיים המורכבים ביותר - מפירוק סיילואים ועד שינויים ארגוניים - לתובנות ניתנות לפעולה.',
    'solutions.siloBusting': 'פירוק סיילואים ושיתוף פעולה',
    'solutions.siloDesc': 'ארגונים מפסידים הון על מחלקות מנותקות. אנו מזהים נתקי תקשורת בזמן אמת ומכוונים מנהלים לגשר על הפערים באופן מיידי.',
    'solutions.siloBenefit1': 'הגברת חדשנות חוצת-ארגון',
    'solutions.siloBenefit2': 'צמצום כפילויות עבודה',
    'solutions.siloBenefit3': 'האצת תהליכי קבלת החלטות',
    'solutions.changeManagement': 'ניהול שינויים (Change Management)',
    'solutions.changeDesc': "בין אם מדובר במיזוגים ורכישות (M&A) או צמיחה מהירה—שינויים נכשלים בגלל דינמיקה אנושית. אנו ממפים את הרשת כדי לאתר את 'סוכני השינוי' שיאיצו את ההטמעה.",
    'solutions.changeBenefit1': 'האצת אינטגרציית M&A',
    'solutions.changeBenefit2': 'ניהול כאבי צמיחה',
    'solutions.changeBenefit3': 'זיהוי חסמים תרבותיים',
    'solutions.talentRetention': 'שימור טאלנטים ושחיקה',
    'solutions.retentionDesc': 'זיהוי סיכוני עזיבה בזמן. ה-AI שלנו מנתח דפוסי תקשורת כדי לזהות שחיקה (עומס יתר תקשורתי) ובידוד (חוסר מעורבות) בשלבים המוקדמים.',
    'solutions.retentionBenefit1': 'חיזוי וזיהוי סכנת שחיקה',
    'solutions.retentionBenefit2': 'איתור טאלנטים מבודדים',
    'solutions.retentionBenefit3': 'חיזוק הקשר בין מנהלים לעובדים',
    'solutions.leadershipDev': 'פיתוח מנהיגות רשתית',
    'solutions.leadershipDesc': "היררכיה נוקשה היא נחלת העבר. אנו מודדים ומאמנים מנהלים להפוך למוקדים (Hubs) של אמון והשפעה, תוך שימוש בדאטה וסימולציות משחקיות.",
    'solutions.leadershipBenefit1': 'מעבר משליטה (Control) לחיבור',
    'solutions.leadershipBenefit2': 'ויזואליזציה של השפעה ניהולית',
    'solutions.leadershipBenefit3': 'תוכניות אימון מבוססות-נתונים',
    'solutions.seeHowItWorks': 'ראו איך זה עובד',
    'solutions.dontSlowDown': 'אל תתנו לבעיות סמויות לעכב אתכם',
    'solutions.getStrategy': 'קבעו פגישת אסטרטגיה',

    // Assessment
    'assessment.badge': 'הערכת טאלנטים מבוססת AI',
    'assessment.title': 'הערכה מבוססת-משחק לכוח העבודה המודרני',
    'assessment.subtitle': 'החליפו שאלונים ארוכים ומתישים במשחקי חשיבה ביקורתית מהירים ומרתקים. אנו עוקבים אחר תגובות התנהגותיות אותנטיות כדי להעניק לכם תובנות בלעדיות על הפוטנציאל האמיתי של המועמדים שלכם.',
    'assessment.whyGames': 'החוויה',
    'assessment.whyGamesTitle': 'התנהגות אותנטית, לא תשובות מתורגלות',
    'assessment.whyGamesDesc': 'בזמן שהמועמדים משחקים, האלגוריתמים המתקדמים שלנו מעריכים את התהליכים הקוגניטיביים שלהם בזמן אמת. זה מייצר בידול חיובי למותג המעסיק שלכם, ומפיק פרופיל כישורים רב-ממדי החף מהטיות של ראיונות מסורתיים.',
    'assessment.feature1': 'ללא צורך בידע מוקדם או הדרכה מקדימה',
    'assessment.feature2': 'נגיש 24/7 מכל מכשיר נייד או מחשב',
    'assessment.feature3': 'מספק חווית מועמד חיובית, משחקית וחדשנית',
    'assessment.processTitle': 'תהליך ההערכה ב-4 שלבים',
    'assessment.step1Title': '1. בניית המסע',
    'assessment.step1Desc': 'יצירת מבחן מותאם אישית עם משחקים גמישים המותאמים לכישורים הספציפיים הנדרשים לתפקיד.',
    'assessment.step2Title': '2. שליחת הקישור',
    'assessment.step2Desc': 'שליחת קישור אישי להרשמה וגישה קלה. ללא צורך בהתקנה או השגחה.',
    'assessment.step3Title': '3. מבחן מבוסס-משחק',
    'assessment.step3Desc': 'המועמדים חווים אתגר מהנה ומרתק שעוקב אחר פתרון הבעיות שלהם בזמן אמת.',
    'assessment.step4Title': '4. דוחות AI מתקדמים',
    'assessment.step4Desc': 'קבלת דירוג מיידי של כל המועמדים עם ניתוח מבוסס AI המדגיש פערי כישורים ונקודות חוזק.',
    'assessment.skillsTitle': 'הכישורים והיכולות שאנו מודדים',
    'assessment.skill1': 'פתרון בעיות מורכבות',
    'assessment.skill1Desc': 'ניתוח נתונים וביצוע פתרונות תחת לחץ זמן ומשאבים.',
    'assessment.skill2': 'זיהוי תבניות (Pattern Recognition)',
    'assessment.skill2Desc': 'זיהוי מגמות וחוקים בסביבות דינמיות ומשתנות.',
    'assessment.skill3': 'תושייה ויוזמה',
    'assessment.skill3Desc': 'מיקסום משאבים מוגבלים וזיהוי הזדמנויות נסתרות.',
    'assessment.ctaTitle': 'מוכנים לשדרג את תהליך הגיוס?',
    'assessment.ctaDesc': 'קבלו פרופיל כישורים מקיף המושווה למדדי בנצ\'מרק גלובליים עבור כל מועמד.',
    'assessment.ctaButton': 'קבעו הדגמה של המערכת',

    // Academy
    'academy.badge': 'סדנאות מנהיגות פרקטיות',
    'academy.title': 'האקדמיה למנהיגות רשתית',
    'academy.subtitle': 'סדנאות מעשיות לעידן הניהול החדש. אנו עוזרים למנהיגים לעבור מתפיסה היררכית לרשתית, באמצעות סימולציות מתקדמות וכלים פרקטיים.',
    'academy.downloadSyllabus': 'הורידו את הסילבוס',
    'academy.methodology': 'המתודולוגיה',
    'academy.theoryMeetsPractice': 'למידה חווייתית ומבוססת נתונים',
    'academy.methodologyDesc1': 'מושגי רשת יכולים להיות מופשטים. כדי לגשר על הפער, אנו משתמשים בסימולציות משחק מתקדמות ככלי אימון. חשבו על זה כ"סימולטור טיסה" למנהלים.',
    'academy.methodologyDesc2': 'המשחקים אינם המטרה — הם האמצעי לתרגול דינמיקות מורכבות כמו הקצאת משאבים, משא ומתן ושיתוף פעולה בסביבה נטולת סיכונים.',
    'academy.methodologyFeature1': 'התנסות פעילה',
    'academy.methodologyFeature2': 'משוב ולמידה בזמן אמת',
    'academy.methodologyFeature3': 'ניתוח והשלכה לעולם האמיתי',
    'academy.strategicSimulations': 'סימולציות אסטרטגיות',
    'academy.interactiveTraining': 'כלי אימון אינטראקטיבי',
    'academy.coreModules': 'מסע המנהיגות ב-6 שלבים',
    'academy.developingPillars': 'תהליך מובנה ורציף לפיתוח ה-DNA הניהולי שלכם.',
    'academy.module1Title': '01. מבוא למנהיגות רשתית',
    'academy.module1Desc': 'מעבר מתפיסה היררכית למודעות רשתית. למדו למפות את הקשרים שלכם, לבנות אמון ולשמר מערכות יחסים מעבר לסיילואים.',
    'academy.module2Title': '02. השפעה ואומץ',
    'academy.module2Desc': 'איך להשפיע ללא סמכות פורמלית. למדו למנף רשתות ארגוניות כדי להוביל שינוי ולבטא אומץ ניהולי.',
    'academy.module3Title': '03. אמון ובטחון פסיכולוגי',
    'academy.module3Desc': 'הליבה האנושית של רשתות. כלים פרקטיים לבניית סביבות שבהן חיבור אותנטי ושיתוף פעולה פרודוקטיבי משגשגים.',
    'academy.module4Title': '04. הסתגלות לשינוי',
    'academy.module4Desc': 'פיתוח גמישות קוגניטיבית והתנהגותית. למדו לקבל החלטות מהירות בתנאי אי-וודאות ולהתגבר על "היתרון הלא הוגן" במציאות משתנה.',
    'academy.module5Title': '05. חשיבה יצירתית',
    'academy.module5Desc': 'צאו מדפוסי חשיבה הרגליים. השתמשו ברשת שלכם כדי לאתגר הנחות יסוד, להרחיב את מרחב הפתרונות ולהוביל חדשנות.',
    'academy.module6Title': '06. קבלת החלטות',
    'academy.module6Desc': 'איזון בין יוזמה ומענה. שלוטו בניהול משאבים מורכב והבינו איך קבוצות מקבלות החלטות בתוך הרשת.',
    'academy.upgradeDNA': 'שדרגו את ה-DNA הניהולי שלכם',
    'academy.upgradeDesc': 'ציידו את המנהלים שלכם בכישורים הנדרשים כדי לנווט בהצלחה בעולם רשתי.',
    'academy.bookWorkshop': 'הזמינו סדנה',

    // About
    'about.mission': 'המשימה שלנו',
    'about.title': 'ארכיטקטים של הארגון הרשתי',
    'about.subtitle': 'אנו כאן כדי להפוך מבנים ארגוניים נוקשים לרשתות חיות, אג\'יליות ומבוססות ערך משותף.',
    'about.orgChartDead': 'לחבר בין אנשים, לייצר ערך.',
    'about.longLiveNetwork': '',
    'about.story1': 'StepAhead הוקמה מתוך חזון לפתח טכנולוגיה חדשנית המבוססת על ניתוח רשתות כדי להעצים שיתופי פעולה ולחבר בין אנשים.',
    'about.story2': 'במשך למעלה ממאה שנה, ארגונים נוהלו כמו מכונות: מלמעלה למטה, בסיילואים, ובנוקשות מחשבתית. אבל העולם השתנה. העבודה כיום היא מורכבת, שיתופית ומהירה.',
    'about.story3': 'שילבנו את המדע של ניתוח רשתות ארגוניות (ONA) יחד עם כלי מנהיגות פרקטיים כדי לתת למנהלים משקפיים חדשים—כאלה שמאפשרים לראות את הזרימה האמיתית של אמון, מידע וחדשנות.',
    'about.whatDrivesUs': 'מה מניע אותנו',
    'about.drive1Title': 'חיבור בין אנשים',
    'about.drive1Desc': 'אנחנו מאמינים בכוחו של הקשר האנושי. המטרה שלנו היא לבנות אמון, לעודד שיתופי פעולה אמיתיים ולחבר בין אנשים מעבר לגבולות הארגון.',
    'about.drive2Title': 'טכנולוגיה חדשנית',
    'about.drive2Desc': 'תחושת בטן היא חשובה, אבל אי אפשר להתווכח עם דאטה. אנו משתמשים בטכנולוגיית ONA מתקדמת כדי למפות את הבלתי-נראה ולהפוך דינמיקות חברתיות לתובנות ברורות.',
    'about.drive3Title': 'החשיבה הרשתית',
    'about.drive3Desc': 'אנחנו נלהבים לעזור למנהלים לעשות את המעבר מהיררכיה נוקשה של "פקודה ושליטה" למנהיגות רשתית המבוססת על השפעה ואג\'יליות.',
    'about.meetLeadership': 'הצוות המוביל',
    'about.sharonRole': 'מייסדת ומנכ"לית תפעול (COO)',
    'about.sharonBio': "מומחית לדינמיקה ארגונית ופתרון קונפליקטים. כבעלים של 'גומא-גבים', המרכז המוביל בישראל לגישור ואימון, שרון דואגת שהטכנולוגיה שלנו תשרת את האנשים, ומתרגמת נתוני רשת לאסטרטגיות בניית אמון בשטח.",
    'about.yuvalRole': 'יועץ אקדמי',
    'about.yuvalBio': 'סמכות עולמית בחקר רשתות חברתיות וארגוניות. ראש תחום מנהיגות ורשתות בבית הספר לניהול WHU, גרמניה. יובל מספק את התשתית המדעית והמתודולוגית לאלגוריתמים של StepAhead.',
    'about.nadavRole': 'מנכ"ל',
    'about.nadavBio': "חלוץ בתחום הלמידה מבוססת-משחק (GBL) והערכת כישורים. עם רקע כמרצה לחשיבה אסטרטגית ומומחה EdTech, נדב מוביל את חזון 'הארגון מבוסס-הכישורים', תוך התמקדות בחשיפת טאלנטים נסתרים דרך טכנולוגיה.",
    'about.joinRevolution': 'הצטרפו למהפכה',
    'about.revolutionDesc': 'בין אם אתם ארגון שמחפש להתפתח או שותפים לדרך, נשמח להכיר.',
    'about.contactUs': 'צרו קשר',

    // CTA
    'cta.title': 'מוכנים לממש את הפוטנציאל הרשתי שלכם?',
    'cta.description': 'גלו את הדפוסים הנסתרים של שיתוף פעולה ומנהיגות בארגון שלכם.',
    'cta.button': 'קבעו הדגמה',

    // Footer
    'footer.tagline': 'ארכיטקטים של הארגון הרשתי. אנו הופכים היררכיות סטטיות לרשתות אנושיות אג\'יליות ומבוססות-נתונים.',
    'footer.solutionsHeading': 'פתרונות',
    'footer.networkLeadership': 'תוכניות מנהיגות רשתית',
    'footer.collaborationIntelligence': 'פלטפורמת ONA',
    'footer.talentSelection': 'איתור והערכת טאלנטים',
    'footer.collabAgent': 'Collab Agent (בטא)',
    'footer.company': 'החברה',
    'footer.aboutUs': 'אודותינו',
    'footer.contact': 'צור קשר',
    'footer.contactUs': 'צור קשר',
    'footer.followLinkedIn': 'עקבו אחרינו ב-LinkedIn',
    'footer.location': 'תל אביב, ישראל',
    'footer.globalOps': 'פעילות גלובלית',
    'footer.rights': 'כל הזכויות שמורות.',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
