import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.aboutUs': 'About Us',
    'nav.platform': 'Platform',
    'nav.solutions': 'Solutions',
    'nav.solutionsDropdown': 'Solutions',
    'nav.talentAcquisition': 'Talent Acquisition',
    'nav.leadershipInnovation': 'Leadership & Innovation',
    'nav.organizationalDynamics': 'Organizational Dynamics',
    'nav.networkSkillsLeadership': 'Network Leadership Programs',
    'nav.collaborationAnalytics': 'Collaboration Intelligence',
    'nav.talentSelection': 'Talent Selection & Assessment',
    'nav.methodology': 'Methodology',
    'nav.aiLabs': 'Collab Agent',
    'nav.academy': 'Academy',
    'nav.process': 'Our Process',
    'nav.skills': 'Network Skills',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.cta': "Let's Talk",

    // Hero (new value proposition)
    'hero.title': 'Network Leadership',
    'hero.subtitle': 'Unlocking the full potential of the Skills-Based Organization',
    'hero.mainTitle': 'Build a Connected, Future-Ready Organization',
    'hero.mainTitleLine1': 'Build a Connected,',
    'hero.mainTitleLine2': 'Future-Ready Organization',
    'hero.mainSubtitle': 'A winning organization is built on its people and how they connect. Use our data-driven tools to empower agile leaders, break down silos, and accelerate organizational innovation.',
    'hero.exploreSolutions': 'Explore Our Solutions',
    'hero.cta': 'Book a Consultation',
    'hero.cta2': 'Our Process',
    'hero.activateNetwork': 'Activate Your Network',
    'hero.meetAgent': 'Meet the Collab Agent',
    'hero.trustedBy': 'Trusted by',
    'hero.trustedBySubtitle': 'Trusted by Forward-Thinking Organizations',

    // Homepage - The 3 Solutions
    'index.pillar1.title': 'Network Leadership Programs',
    'index.pillar1.text': 'Train managers on how to build relationships, connect the right people, and lead effectively across teams without relying on formal authority.',
    'index.pillar1.benefit1': 'Identify hidden bottlenecks',
    'index.pillar1.benefit2': 'Cultivate high-trust relationships',
    'index.pillar1.benefit3': 'Accelerate cross-functional alignment',
    'index.pillar1.button': 'Explore Leadership Programs',
    'index.pillar2.title': 'Collaboration Intelligence',
    'index.pillar2.text': 'Advanced network mapping tools that show you exactly how your teams actually work together to identify bottlenecks and reveal hidden talent.',
    'index.pillar2.button': 'Discover ONA Platform',
    'index.pillar3.title': 'Talent Selection & Assessment',
    'index.pillar3.text': 'Data-driven, game-based cognitive assessments to evaluate and hire candidates who have the right skills to integrate into your network.',
    'index.pillar3.button': 'Discover Talent Tools',

    // Homepage - Our Methodology
    'index.philosophy.title': 'The Org Chart is a Myth. The Network is Reality.',
    'index.philosophy.text': 'Value is no longer created in silos—it flows through invisible networks. We provide the methodology and tools to transition your company from a rigid hierarchy into an agile, connected ecosystem.',

    // Homepage - The Future (AI Collab Agent)
    'index.future.title': 'Meet Your Collab Agent (Beta)',
    'index.future.text': 'The right person is already in your contacts. Tell us what you\'re working on — and we\'ll find the exact people who can help you right now. Not the obvious ones. The ones you forgot you knew. Our AI agent sits directly in your workflow to help you leverage your existing network effectively and connect you with the right people at the right time.',
    'index.future.badge': 'AI Labs',
    'index.future.cta': 'Join the Waitlist',
    'index.future.ctaAlt': 'Become a Design Partner',

    // Myth Section
    'myth.title': 'The Org Chart is a Myth',
    'myth.subtitle': 'The Network is Reality',
    'myth.description': 'Value is no longer created in silos — it flows through invisible networks. We help you see, understand, and optimize these hidden connections.',

    // Process
    'process.title': 'From Hidden Data to Organizational Impact',
    'process.subtitle': 'The 4-Step Process',
    'process.step1.title': 'Identify',
    'process.step1.subtitle': 'Mapping',
    'process.step1.desc': 'Find your "Invisible Heroes" — the most connected and influential people based on actual collaboration data.',
    'process.step2.title': 'Diagnose',
    'process.step2.subtitle': 'Profiling',
    'process.step2.desc': 'Assess specific relational skills: ability to build trust, exert influence, and bridge disparate groups.',
    'process.step3.title': 'Developing',
    'process.step3.subtitle': 'Skills',
    'process.step3.desc': 'Targeted development programs to strengthen network leadership capabilities.',
    'process.step4.title': 'Implementing',
    'process.step4.subtitle': 'AI Agent',
    'process.step4.desc': 'AI-powered coaching and real-time connectivity insights for continuous improvement.',

    // Skills
    'skills.title': 'The Network Mindset',
    'skills.subtitle': 'Essential Skills for the Agile Era',
    'skills.hub.title': 'Network Hub',
    'skills.hub.desc': 'A person at the center of conversations, sought for advice and guidance. Builds high-trust relationships.',
    'skills.bridge.title': 'Strategic Bridge',
    'skills.bridge.desc': 'Connects between units, ranks, and different fields of expertise. Facilitates alignment and balance.',
    'skills.gardener.title': 'Network Gardener',
    'skills.gardener.desc': 'Maintains deep, local, continuous relationships. Strengthens high-quality relationships.',
    'skills.pioneer.title': 'Network Pioneer',
    'skills.pioneer.desc': 'Constantly searches for new connections and domains. Builds high-diversity relationships.',

    // Index
    'index.turnOrgChart': 'Turn Your Org Chart Into a Living Network',
    'index.orgChartDesc': 'Move beyond static hierarchies. We use Organizational Network Analysis (ONA) to reveal how work really gets done.',
    'index.innovation': 'Innovation & Silo Busting',
    'index.innovationDesc': 'Innovation happens at the intersection. We visualize structural holes and bridge disconnected silos to speed up ideation.',
    'index.retention': 'Retention & Burnout',
    'index.retentionDesc': 'Spot flight risks before they resign. Visualize isolated nodes (purple) vs. embedded employees to predict attrition.',
    'index.leadership': 'Network Leadership',
    'index.leadershipDesc': 'Shift from hierarchy to hub. Identify and train your central connectors to influence change and drive strategy.',
    'index.howWeDoIt': 'How We Do It',
    'index.explorePlatform': 'Explore The Platform',
    'index.risk': 'Risk',

    // Platform
    'platform.os': 'The OS for the Networked Organization',
    'platform.title': 'The Platform',
    'platform.subtitle': 'A powerful fusion of data, psychology, and AI that transforms static hierarchies into intelligent human networks.',
    'platform.onaEngine': 'The ONA Engine',
    'platform.visualizeInvisible': 'Visualize the Invisible',
    'platform.onaDesc': 'Passive Data: We map the actual structure and flow of your organization. Our engine identifies bottlenecks, isolated employees, and hidden influencers that traditional org charts miss.',
    'platform.onaFeature1': 'Visualize communication flows',
    'platform.onaFeature2': 'Identify key influencers',
    'platform.onaFeature3': 'Detect silos and isolation',
    'platform.networkProfiling': 'Network Profiling',
    'platform.deepInsight': 'Deep Behavioral Insight',
    'platform.profilingDesc': "Active Data: A research-backed questionnaire designed to uncover each employee's unique Network Persona. Identify natural strengths and personalized growth areas.",
    'platform.profilingFeature1': 'Discover your Network Persona',
    'platform.profilingFeature2': 'Research-backed methodology',
    'platform.profilingFeature3': 'Personalized growth insights',
    'platform.collabAgent': 'The Collab Agent',
    'platform.actionableNudges': 'Actionable Nudges',
    'platform.agentDesc': "Intervention: Our AI provides real-time 'nudges'. The agent suggests who employees should connect with to bridge gaps and improve overall network health.",
    'platform.agentFeature1': 'AI-driven connection suggestions',
    'platform.agentFeature2': 'Integration with Slack/Teams',
    'platform.agentFeature3': 'Actionable daily insights',
    'platform.seeHowItWorks': 'See How It Works',
    'platform.readyTransform': 'Ready to Transform Your Organization?',
    'platform.joinCompanies': 'Join the forward-thinking companies already using StepAhead.',
    'platform.bookDemo': 'Book a Demo',
    'platform.contactSales': 'Contact Sales',

    // Solutions
    'solutions.badge': 'SOLUTIONS FOR EVERY CHALLENGE',
    'solutions.title': 'Solving the Complexity of Modern Work',
    'solutions.subtitle': 'From breaking down silos to navigating complex organizational changes—we turn your biggest human challenges into manageable data insights.',
    'solutions.siloBusting': 'Silo Busting & Collaboration',
    'solutions.siloDesc': 'Organizations lose millions on disconnected departments. We identify communication breaks in real-time and nudge leaders to bridge the gaps instantly.',
    'solutions.siloBenefit1': 'Increase cross-functional innovation',
    'solutions.siloBenefit2': 'Reduce duplication of work',
    'solutions.siloBenefit3': 'Speed up decision making',
    'solutions.changeManagement': 'Change Management',
    'solutions.changeDesc': "Whether it's M&A, hyper-growth, or restructuring—change fails due to people dynamics. We map the network to identify key 'Change Agents' who can accelerate adoption and integration.",
    'solutions.changeBenefit1': 'Accelerate M&A integration',
    'solutions.changeBenefit2': 'Manage rapid growth pains',
    'solutions.changeBenefit3': 'Identify cultural blockers',
    'solutions.talentRetention': 'Talent Retention & Burnout',
    'solutions.retentionDesc': 'Spot flight risks before they resign. Our AI analyzes communication patterns to detect burnout (over-collaboration) and isolation (disengagement) early.',
    'solutions.retentionBenefit1': 'Predict burnout risk',
    'solutions.retentionBenefit2': 'Identify isolated high-performers',
    'solutions.retentionBenefit3': 'Improve manager-employee connection',
    'solutions.leadershipDev': 'Network Leadership Development',
    'solutions.leadershipDesc': "Hierarchy is dead. We measure and train managers on how to become 'Hubs' of trust and influence, using data-driven insights and gamified simulations.",
    'solutions.leadershipBenefit1': 'Move from command to connect',
    'solutions.leadershipBenefit2': 'Visualize leadership impact',
    'solutions.leadershipBenefit3': 'Data-driven coaching plans',
    'solutions.seeHowItWorks': 'See How It Works',
    'solutions.dontSlowDown': "Don't let invisible problems slow you down",
    'solutions.getStrategy': 'Get a Strategy Session',

    // Academy
    'academy.badge': 'PRACTICAL LEADERSHIP WORKSHOPS',
    'academy.title': 'Network Leadership Academy',
    'academy.subtitle': 'Practical workshops for the new era of management. We help leaders shift from a hierarchical mindset to a networked one, using advanced simulations and practical tools.',
    'academy.downloadSyllabus': 'Download Syllabus',
    'academy.methodology': 'THE METHODOLOGY',
    'academy.theoryMeetsPractice': 'Theory Meets Practice',
    'academy.methodologyDesc1': 'Network concepts can be abstract. To bridge the gap, we use advanced simulations (powered by Accelium) as a training aid.',
    'academy.methodologyDesc2': 'Think of it as a "Flight Simulator" for management. The games aren\'t the goal—they are the means to practice complex dynamics like resource allocation, negotiation, and collaboration in a risk-free environment.',
    'academy.methodologyFeature1': 'Active experimentation',
    'academy.methodologyFeature2': 'Immediate feedback loops',
    'academy.methodologyFeature3': 'Real-world analogy analysis',
    'academy.strategicSimulations': 'Strategic Simulations',
    'academy.interactiveTraining': 'Interactive Training Aid',
    'academy.coreModules': 'Core Modules',
    'academy.developingPillars': 'Developing the 4 Pillars of Network Intelligence',
    'academy.trustBuilding': 'Trust Building',
    'academy.trustDesc': 'Creating psychological safety in hybrid teams.',
    'academy.influence': 'Influence Without Authority',
    'academy.influenceDesc': 'Leading complex projects across silos.',
    'academy.networkMindset': 'Network Mindset',
    'academy.mindsetDesc': "Shifting from 'Command & Control' to 'Connect & Collaborate'.",
    'academy.strategicConnecting': 'Strategic Connecting',
    'academy.connectingDesc': 'Identifying and leveraging key organizational bridges.',
    'academy.upgradeDNA': 'Upgrade Your Management DNA',
    'academy.upgradeDesc': 'Equip your leaders with the skills they need to navigate a networked world.',
    'academy.bookWorkshop': 'Book a Workshop',

    // About
    'about.mission': 'OUR MISSION',
    'about.title': 'Architects of the Networked Organization',
    'about.subtitle': 'We exist to transform static hierarchies into living, breathing, adaptive networks of shared value.',
    'about.orgChartDead': 'Unlock the Power of Your People.',
    'about.longLiveNetwork': 'Welcome to the Networked Organization.',
    'about.story1': 'StepAhead was founded with the vision of developing innovative technology based on network analysis to enable collaboration and connect people.',
    'about.story2': 'For over a century, organizations were managed like machines: top-down, siloed, and rigid. But the world has changed. Work today is complex, collaborative, and fast-paced.',
    'about.story3': 'We combined the science of Organizational Network Analysis (ONA) with practical leadership tools to give leaders a new pair of glasses—ones that see the actual flow of trust, information, and innovation.',
    'about.whatDrivesUs': 'What Drives Us',
    'about.drive1Title': 'Connecting People',
    'about.drive1Desc': 'We believe in the power of human connection. We exist to build trust, foster genuine collaboration, and bring people together across organizational boundaries.',
    'about.drive2Title': 'Innovative Technology',
    'about.drive2Desc': 'Gut feeling is important, but data is undeniable. We use advanced Network Analysis (ONA) to map the invisible and turn complex social dynamics into clear insights.',
    'about.drive3Title': 'The Network Mindset',
    'about.drive3Desc': 'We are passionate about guiding leaders away from rigid, command-and-control hierarchies and towards agile, influence-based network leadership.',
    'about.meetLeadership': 'Meet the Leadership',
    'about.sharonRole': 'Founder & COO',
    'about.sharonBio': "An expert in organizational dynamics and conflict resolution. As the owner of 'Gome-Gevim', Israel's leading mediation center, Sharon ensures our technology serves the people, translating network data into actionable strategies that build trust.",
    'about.yuvalRole': 'Academic Advisor',
    'about.yuvalBio': 'A world-renowned authority on Network Theory. Chair of Leadership and Networks at WHU School of Management, Germany. Yuval provides the scientific backbone to our ONA algorithms and methodology.',
    'about.nadavRole': 'CEO',
    'about.nadavBio': "A pioneer in game-based assessment and skill development. With a background as a strategic thinking lecturer and EdTech expert, Nadav leads the vision of the 'Skills-Based Organization', focusing on uncovering hidden talent through technology.",
    'about.joinRevolution': 'Join the Revolution',
    'about.revolutionDesc': "Whether you are an organization looking to evolve or a partner looking to collaborate, we'd love to connect.",
    'about.contactUs': 'Contact Us',

    // CTA
    'cta.title': 'Ready to Unlock Your Network Potential?',
    'cta.description': 'Discover the hidden patterns of collaboration and leadership within your organization.',
    'cta.button': 'Schedule a Demo',

    // Footer
    'footer.tagline': 'Architects of the Networked Organization. We transform static hierarchies into adaptive, data-driven human networks.',
    'footer.solutionsHeading': 'Solutions',
    'footer.networkLeadership': 'Network Leadership Programs',
    'footer.collaborationIntelligence': 'Collaboration Intelligence',
    'footer.talentSelection': 'Talent Selection & Assessment',
    'footer.collabAgent': 'Collab Agent (Beta)',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.contactUs': 'Contact Us',
    'footer.followLinkedIn': 'Follow us on LinkedIn',
    'footer.location': 'Tel Aviv, Israel',
    'footer.globalOps': 'Global Operations',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.about': 'אודותינו',
    'nav.aboutUs': 'אודותינו',
    'nav.platform': 'פלטפורמה',
    'nav.solutions': 'פתרונות',
    'nav.solutionsDropdown': 'פתרונות',
    'nav.talentAcquisition': 'גיוס טאלנטים',
    'nav.leadershipInnovation': 'מנהיגות וחדשנות',
    'nav.organizationalDynamics': 'דינמיקה ארגונית',
    'nav.networkSkillsLeadership': 'תוכניות מנהיגות רשתית',
    'nav.collaborationAnalytics': 'בינה שיתופית',
    'nav.talentSelection': 'איתור והערכת טאלנטים',
    'nav.methodology': 'מתודולוגיה',
    'nav.aiLabs': 'Collab Agent',
    'nav.academy': 'אקדמיה',
    'nav.process': 'התהליך שלנו',
    'nav.skills': 'כישורי רשת',
    'nav.contact': 'צור קשר',
    'nav.getStarted': 'התחילו עכשיו',
    'nav.cta': 'דברו איתנו',

    // Hero
    'hero.title': 'מנהיגות רשתית',
    'hero.subtitle': 'מימוש מלוא הפוטנציאל של הארגון מבוסס-הכישורים',
    'hero.mainTitle': 'לבנות ארגון מחובר שמוכן לאתגרי המחר',
    'hero.mainTitleLine1': 'לבנות ארגון מחובר',
    'hero.mainTitleLine2': 'שמוכן לאתגרי המחר',
    'hero.mainSubtitle': 'הדרך לארגון מנצח עוברת באנשים שלו ובאופן שבו הם מחוברים. השתמשו בכלים מבוססי הנתונים שלנו כדי לחזק מנהיגים אג\'יליים, לפרק סיילואים, ולהאיץ חדשנות ארגונית.',
    'hero.exploreSolutions': 'גלו את הפתרונות שלנו',
    'hero.cta': 'קבעו שיחת ייעוץ',
    'hero.cta2': 'התהליך שלנו',
    'hero.activateNetwork': 'הפעילו את הרשת שלכם',
    'hero.meetAgent': 'הכירו את Collab Agent',
    'hero.trustedBy': 'סומכים עלינו',
    'hero.trustedBySubtitle': 'ארגונים מובילים שסומכים עלינו',

    // Homepage - The 3 Solutions
    'index.pillar1.title': 'תוכניות מנהיגות רשתית',
    'index.pillar1.text': 'הכשרת מנהלים לבניית יחסים, חיבור האנשים הנכונים והובלה אפקטיבית בין צוותים - ללא הסתמכות על סמכות פורמלית.',
    'index.pillar1.benefit1': 'זיהוי צווארי בקבוק נסתרים',
    'index.pillar1.benefit2': 'טיפוח יחסי אמון גבוהים',
    'index.pillar1.benefit3': 'האצת ממשקי עבודה חוצי-ארגון',
    'index.pillar1.button': 'גלו תוכניות מנהיגות',
    'index.pillar2.title': 'בינה שיתופית',
    'index.pillar2.text': 'כלי מיפוי רשת מתקדמים שמראים בדיוק איך הצוותים שלכם עובדים יחד – לזיהוי צווארי בקבוק וחשיפת טאלנטים נסתרים.',
    'index.pillar2.button': 'גלו את פלטפורמת ONA',
    'index.pillar3.title': 'איתור והערכת טאלנטים',
    'index.pillar3.text': 'הערכות קוגניטיביות מבוססות-משחק לזיהוי מועמדים עם הכישורים והפוטנציאל להשתלב ברשת הארגונית שלכם.',
    'index.pillar3.button': 'גלו כלי הערכה',

    // Homepage - Our Methodology
    'index.philosophy.title': 'העץ הארגוני הוא מיתוס. הרשת היא המציאות.',
    'index.philosophy.text': 'ערך כבר לא נוצר בממגורות — הוא זורם דרך רשתות בלתי נראות. אנו מספקים את המתודולוגיה והכלים להעביר את החברה שלכם מהיררכיה נוקשה למערכת אקולוגית אג\'ילית ומחוברת.',

    // Homepage - The Future (AI Collab Agent)
    'index.future.title': 'הכירו את Collab Agent (בטא)',
    'index.future.text': 'האדם הנכון כבר נמצא באנשי הקשר שלכם. ספרו לנו על מה אתם עובדים — ואנו נמצא את האנשים המדויקים שיכולים לעזור לכם עכשיו. לא המובנים מאליהם, אלא אלה ששכחתם שאתם מכירים. סוכן ה-AI שלנו משתלב ישירות בסביבת העבודה שלכם כדי לחבר אתכם לאנשים הנכונים בזמן הנכון.',
    'index.future.badge': 'AI Labs',
    'index.future.cta': 'הצטרפו לרשימת ההמתנה',
    'index.future.ctaAlt': 'הפכו לשותף עיצוב (Design Partner)',

    // Myth Section
    'myth.title': 'העץ הארגוני הוא מיתוס',
    'myth.subtitle': 'הרשת היא המציאות',
    'myth.description': 'ערך כבר לא נוצר בממגורות — הוא זורם דרך רשתות בלתי נראות. אנחנו עוזרים לכם לראות, להבין ולייעל את הקשרים הנסתרים האלה.',

    // Process
    'process.title': 'מנתונים נסתרים להשפעה ארגונית',
    'process.subtitle': 'תהליך 4 השלבים',
    'process.step1.title': 'זיהוי',
    'process.step1.subtitle': 'מיפוי',
    'process.step1.desc': 'מצאו את ה"גיבורים הנסתרים" — האנשים המחוברים והמשפיעים ביותר על בסיס נתוני שיתוף פעולה אמיתיים.',
    'process.step2.title': 'אבחון',
    'process.step2.subtitle': 'אפיון רשתי',
    'process.step2.desc': 'הערכת כישורים יחסיים ספציפיים: היכולת לבנות אמון, לייצר השפעה ולגשר בין קבוצות.',
    'process.step3.title': 'פיתוח',
    'process.step3.subtitle': 'כישורים',
    'process.step3.desc': 'תוכניות פיתוח ממוקדות לחיזוק יכולות מנהיגות רשתית.',
    'process.step4.title': 'יישום',
    'process.step4.subtitle': 'סוכן AI',
    'process.step4.desc': 'אימון מונע AI ותובנות קישוריות בזמן אמת לשיפור מתמיד.',

    // Skills
    'skills.title': 'החשיבה הרשתית',
    'skills.subtitle': 'כישורים חיוניים לעידן האג\'ילי',
    'skills.hub.title': 'צומת מרכזי (Hub)',
    'skills.hub.desc': 'אדם במרכז השיחות, אליו פונים לייעוץ והדרכה. בונה יחסי אמון גבוהים.',
    'skills.bridge.title': 'מגשר אסטרטגי',
    'skills.bridge.desc': 'מחבר בין יחידות, דרגים ותחומי מומחיות שונים. מאפשר סנכרון ואיזון.',
    'skills.gardener.title': 'מטפח רשת (Gardener)',
    'skills.gardener.desc': 'מקיים קשרים עמוקים, מקומיים ורציפים. מחזק מערכות יחסים איכותיות.',
    'skills.pioneer.title': 'חלוץ רשת (Pioneer)',
    'skills.pioneer.desc': 'מחפש כל הזמן קשרים ותחומים חדשים. בונה רשת בעלת גיוון גבוה.',

    // Index
    'index.turnOrgChart': 'הפכו את העץ הארגוני לרשת חיה',
    'index.orgChartDesc': 'התקדמו מעבר להיררכיה הסטטית. אנו משתמשים בניתוח רשתות ארגוניות (ONA) כדי לחשוף איך העבודה באמת מתבצעת.',
    'index.innovation': 'מהירות וחדשנות',
    'index.innovationDesc': 'חדשנות קורית בחיבורים. המערכת מזהה נתקים ומגשרת בין מחלקות מבודדות.',
    'index.retention': 'שימור טאלנטים',
    'index.retentionDesc': 'זהו עובדים מבודדים לפני שהם עוזבים. ניתוח רשתי מתקדם לחיזוי סיכוני עזיבה ושחיקה.',
    'index.leadership': 'מנהיגות מודרנית',
    'index.leadershipDesc': 'מנהלים לומדים להשפיע דרך אמון וחיבורים (Hubs), ולא רק מתוקף סמכותם.',
    'index.howWeDoIt': 'איך אנחנו עושים את זה',
    'index.explorePlatform': 'גלו את הפלטפורמה',
    'index.risk': 'ניהול סיכונים',

    // Platform
    'platform.os': 'מערכת ההפעלה של הארגון המחובר',
    'platform.title': 'הפלטפורמה שלנו',
    'platform.subtitle': 'שילוב עוצמתי של דאטה, פסיכולוגיה ובינה מלאכותית, ההופך היררכיה סטטית לרשת אנושית חכמה.',
    'platform.onaEngine': 'מנוע ה-ONA',
    'platform.visualizeInvisible': 'לראות את הבלתי נראה',
    'platform.onaDesc': 'דאטה פסיבי: מיפוי המבנה והזרימה האמיתיים של הארגון. המערכת מזהה צווארי בקבוק, עובדים מבודדים ומוקדי השפעה נסתרים שלא מופיעים בעץ הארגוני.',
    'platform.onaFeature1': 'מיפוי זרימת תקשורת',
    'platform.onaFeature2': 'זיהוי משפיענים מרכזיים',
    'platform.onaFeature3': 'איתור סיילואים ובידוד ארגוני',
    'platform.networkProfiling': 'פרופיל רשתי',
    'platform.deepInsight': 'מעבר למשחוק: תובנות התנהגותיות',
    'platform.profilingDesc': 'דאטה אקטיבי: שאלון מבוסס-מחקרית שנועד לחשוף את ה"פרסונה הרשתית" של כל עובד. גלו חוזקות טבעיות ותחומי צמיחה אישיים.',
    'platform.profilingFeature1': 'גלו את הפרסונה הרשתית שלכם',
    'platform.profilingFeature2': 'מתודולוגיה מבוססת מחקר אקדמי',
    'platform.profilingFeature3': 'תובנות אישיות לצמיחה',
    'platform.collabAgent': 'סוכן ה-AI',
    'platform.actionableNudges': 'הכוונות (Nudges) לפעולה',
    'platform.agentDesc': "התערבות אקטיבית: סוכן ה-AI שלנו מספק 'הכוונות' (Nudges) בזמן אמת. המערכת מזהה למי כדאי לכל עובד לפנות כדי לגשר על פערים ולשפר את בריאות הרשת הארגונית.",
    'platform.agentFeature1': 'המלצות לחיבורים מבוססות AI',
    'platform.agentFeature2': 'אינטגרציה חלקה ל-Teams/Slack',
    'platform.agentFeature3': 'תובנות יומיות לפעולה',
    'platform.seeHowItWorks': 'ראו איך זה עובד',
    'platform.readyTransform': 'מוכנים להפוך את הארגון לרשתי?',
    'platform.joinCompanies': 'הצטרפו לארגונים החדשניים שכבר משתמשים ב-StepAhead.',
    'platform.bookDemo': 'קבעו הדגמה',
    'platform.contactSales': 'דברו עם צוות המכירות',

    // Solutions
    'solutions.badge': 'פתרונות לכל אתגר ארגוני',
    'solutions.title': 'פתרונות לארגונים בצמיחה ושינוי',
    'solutions.subtitle': 'אנו הופכים את האתגרים האנושיים המורכבים ביותר - מפירוק סיילואים ועד שינויים ארגוניים - לתובנות ניתנות לפעולה.',
    'solutions.siloBusting': 'פירוק סיילואים ושיתוף פעולה',
    'solutions.siloDesc': 'ארגונים מפסידים הון על מחלקות מנותקות. אנו מזהים נתקי תקשורת בזמן אמת ומכוונים מנהלים לגשר על הפערים באופן מיידי.',
    'solutions.siloBenefit1': 'הגברת חדשנות חוצת-ארגון',
    'solutions.siloBenefit2': 'צמצום כפילויות עבודה',
    'solutions.siloBenefit3': 'האצת תהליכי קבלת החלטות',
    'solutions.changeManagement': 'ניהול שינויים (Change Management)',
    'solutions.changeDesc': "בין אם מדובר במיזוגים ורכישות (M&A) או צמיחה מהירה—שינויים נכשלים בגלל דינמיקה אנושית. אנו ממפים את הרשת כדי לאתר את 'סוכני השינוי' שיאיצו את ההטמעה.",
    'solutions.changeBenefit1': 'האצת אינטגרציית M&A',
    'solutions.changeBenefit2': 'ניהול כאבי צמיחה',
    'solutions.changeBenefit3': 'זיהוי חסמים תרבותיים',
    'solutions.talentRetention': 'שימור טאלנטים ושחיקה',
    'solutions.retentionDesc': 'זיהוי סיכוני עזיבה בזמן. ה-AI שלנו מנתח דפוסי תקשורת כדי לזהות שחיקה (עומס יתר תקשורתי) ובידוד (חוסר מעורבות) בשלבים המוקדמים.',
    'solutions.retentionBenefit1': 'חיזוי וזיהוי סכנת שחיקה',
    'solutions.retentionBenefit2': 'איתור טאלנטים מבודדים',
    'solutions.retentionBenefit3': 'חיזוק הקשר בין מנהלים לעובדים',
    'solutions.leadershipDev': 'פיתוח מנהיגות רשתית',
    'solutions.leadershipDesc': "היררכיה נוקשה היא נחלת העבר. אנו מודדים ומאמנים מנהלים להפוך למוקדים (Hubs) של אמון והשפעה, תוך שימוש בדאטה וסימולציות משחקיות.",
    'solutions.leadershipBenefit1': 'מעבר משליטה (Control) לחיבור',
    'solutions.leadershipBenefit2': 'ויזואליזציה של השפעה ניהולית',
    'solutions.leadershipBenefit3': 'תוכניות אימון מבוססות-נתונים',
    'solutions.seeHowItWorks': 'ראו איך זה עובד',
    'solutions.dontSlowDown': 'אל תתנו לבעיות סמויות לעכב אתכם',
    'solutions.getStrategy': 'קבעו פגישת אסטרטגיה',

    // Academy
    'academy.badge': 'סדנאות מנהיגות פרקטיות',
    'academy.title': 'האקדמיה למנהיגות רשתית',
    'academy.subtitle': 'סדנאות מעשיות לעידן הניהול החדש. אנו עוזרים למנהיגים לעבור מתפיסה היררכית לרשתית, באמצעות סימולציות מתקדמות וכלים פרקטיים.',
    'academy.downloadSyllabus': 'הורידו את הסילבוס',
    'academy.methodology': 'המתודולוגיה',
    'academy.theoryMeetsPractice': 'תיאוריה פוגשת פרקטיקה',
    'academy.methodologyDesc1': 'מושגי רשת יכולים להיות מופשטים. כדי לגשר על הפער, אנו משתמשים בסימולציות ממוחשבות מתקדמות (בשיתוף Accelium) ככלי אימון.',
    'academy.methodologyDesc2': 'חשבו על זה כ"סימולטור טיסה" למנהלים. המשחקים אינם המטרה — הם האמצעי לתרגול דינמיקות מורכבות כמו הקצאת משאבים, משא ומתן ושיתוף פעולה בסביבה נטולת סיכונים.',
    'academy.methodologyFeature1': 'התנסות פעילה',
    'academy.methodologyFeature2': 'משוב ולמידה בזמן אמת',
    'academy.methodologyFeature3': 'ניתוח והשלכה לעולם האמיתי',
    'academy.strategicSimulations': 'סימולציות אסטרטגיות',
    'academy.interactiveTraining': 'כלי אימון אינטראקטיבי',
    'academy.coreModules': 'מודולי הליבה',
    'academy.developingPillars': 'פיתוח 4 עמודי התווך של אינטליגנציה רשתית',
    'academy.trustBuilding': 'בניית אמון',
    'academy.trustDesc': 'יצירת ביטחון פסיכולוגי בצוותים היברידיים וגלובליים.',
    'academy.influence': 'השפעה ללא סמכות',
    'academy.influenceDesc': 'הובלת פרויקטים מורכבים חוצי-ארגון.',
    'academy.networkMindset': 'חשיבה רשתית',
    'academy.mindsetDesc': "מעבר מ'פיקוד ושליטה' ל'חיבור ושיתוף פעולה'.",
    'academy.strategicConnecting': 'רישות אסטרטגי',
    'academy.connectingDesc': 'זיהוי ומינוף צמתים וגשרים ארגוניים.',
    'academy.upgradeDNA': 'שדרגו את ה-DNA הניהולי שלכם',
    'academy.upgradeDesc': 'ציידו את המנהלים שלכם בכישורים הנדרשים כדי לנווט בהצלחה בעולם רשתי.',
    'academy.bookWorkshop': 'הזמינו סדנה',

    // About
    'about.mission': 'המשימה שלנו',
    'about.title': 'ארכיטקטים של הארגון הרשתי',
    'about.subtitle': 'אנו כאן כדי להפוך מבנים ארגוניים נוקשים לרשתות חיות, אג\'יליות ומבוססות ערך משותף.',
    'about.orgChartDead': 'לשחרר את הפוטנציאל האנושי.',
    'about.longLiveNetwork': 'ברוכים הבאים לארגון המחובר.',
    'about.story1': 'StepAhead הוקמה מתוך חזון לפתח טכנולוגיה חדשנית המבוססת על ניתוח רשתות כדי להעצים שיתופי פעולה ולחבר בין אנשים.',
    'about.story2': 'במשך למעלה ממאה שנה, ארגונים נוהלו כמו מכונות: מלמעלה למטה, בסיילואים, ובנוקשות מחשבתית. אבל העולם השתנה. העבודה כיום היא מורכבת, שיתופית ומהירה.',
    'about.story3': 'שילבנו את המדע של ניתוח רשתות ארגוניות (ONA) יחד עם כלי מנהיגות פרקטיים כדי לתת למנהלים משקפיים חדשים—כאלה שמאפשרים לראות את הזרימה האמיתית של אמון, מידע וחדשנות.',
    'about.whatDrivesUs': 'מה מניע אותנו',
    'about.drive1Title': 'חיבור בין אנשים',
    'about.drive1Desc': 'אנחנו מאמינים בכוחו של הקשר האנושי. המטרה שלנו היא לבנות אמון, לעודד שיתופי פעולה אמיתיים ולחבר בין אנשים מעבר לגבולות הארגון.',
    'about.drive2Title': 'טכנולוגיה חדשנית',
    'about.drive2Desc': 'תחושת בטן היא חשובה, אבל אי אפשר להתווכח עם דאטה. אנו משתמשים בטכנולוגיית ONA מתקדמת כדי למפות את הבלתי-נראה ולהפוך דינמיקות חברתיות לתובנות ברורות.',
    'about.drive3Title': 'החשיבה הרשתית',
    'about.drive3Desc': 'אנחנו נלהבים לעזור למנהלים לעשות את המעבר מהיררכיה נוקשה של "פקודה ושליטה" למנהיגות רשתית המבוססת על השפעה ואג\'יליות.',
    'about.meetLeadership': 'הצוות המוביל',
    'about.sharonRole': 'מייסדת ומנכ"לית תפעול (COO)',
    'about.sharonBio': "מומחית לדינמיקה ארגונית ופתרון קונפליקטים. כבעלים של 'גומא-גבים', המרכז המוביל בישראל לגישור ואימון, שרון דואגת שהטכנולוגיה שלנו תשרת את האנשים, ומתרגמת נתוני רשת לאסטרטגיות בניית אמון בשטח.",
    'about.yuvalRole': 'יועץ אקדמי',
    'about.yuvalBio': 'סמכות עולמית בחקר רשתות חברתיות וארגוניות. ראש תחום מנהיגות ורשתות בבית הספר לניהול WHU, גרמניה. יובל מספק את התשתית המדעית והמתודולוגית לאלגוריתמים של StepAhead.',
    'about.nadavRole': 'מנכ"ל',
    'about.nadavBio': "חלוץ בתחום הלמידה מבוססת-משחק (GBL) והערכת כישורים. עם רקע כמרצה לחשיבה אסטרטגית ומומחה EdTech, נדב מוביל את חזון 'הארגון מבוסס-הכישורים', תוך התמקדות בחשיפת טאלנטים נסתרים דרך טכנולוגיה.",
    'about.joinRevolution': 'הצטרפו למהפכה',
    'about.revolutionDesc': 'בין אם אתם ארגון שמחפש להתפתח או שותפים לדרך, נשמח להכיר.',
    'about.contactUs': 'צרו קשר',

    // CTA
    'cta.title': 'מוכנים לממש את הפוטנציאל הרשתי שלכם?',
    'cta.description': 'גלו את הדפוסים הנסתרים של שיתוף פעולה ומנהיגות בארגון שלכם.',
    'cta.button': 'קבעו הדגמה',

    // Footer
    'footer.tagline': 'ארכיטקטים של הארגון הרשתי. אנו הופכים היררכיות סטטיות לרשתות אנושיות אג\'יליות ומבוססות-נתונים.',
    'footer.solutionsHeading': 'פתרונות',
    'footer.networkLeadership': 'תוכניות מנהיגות רשתית',
    'footer.collaborationIntelligence': 'בינה שיתופית',
    'footer.talentSelection': 'איתור והערכת טאלנטים',
    'footer.collabAgent': 'Collab Agent (בטא)',
    'footer.company': 'החברה',
    'footer.aboutUs': 'אודותינו',
    'footer.contact': 'צור קשר',
    'footer.contactUs': 'צור קשר',
    'footer.followLinkedIn': 'עקבו אחרינו ב-LinkedIn',
    'footer.location': 'תל אביב, ישראל',
    'footer.globalOps': 'פעילות גלובלית',
    'footer.rights': 'כל הזכויות שמורות.',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
